"""inventory vertical flow

Revision ID: 0004_inventory_vertical_flow
Revises: 0003_journal_responsibility
Create Date: 2026-07-20 12:52:33.154105
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_inventory_vertical_flow"
down_revision: str | None = "0003_journal_responsibility"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS assets")
    op.drop_constraint(
        "ck_role_assignments_role_allowed",
        "role_assignments",
        schema="identity",
        type_="check",
    )
    op.create_check_constraint(
        "ck_role_assignments_role_allowed",
        "role_assignments",
        "role_code IN ('MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',"
        "'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',"
        "'RISK_ADMIN','SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR')",
        schema="identity",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_blobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("expected_sha256", sa.String(length=64), nullable=False),
        sa.Column("expected_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("access_scope", sa.String(length=40), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=True),
        sa.Column("encryption_algorithm", sa.String(length=40), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("completed_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','READY','FAILED')", name=op.f("ck_evidence_blobs_status_allowed")
        ),
        sa.CheckConstraint(
            "expected_size >= 0 AND expected_size <= 26214400",
            name=op.f("ck_evidence_blobs_size_allowed"),
        ),
        sa.CheckConstraint(
            "expected_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_evidence_blobs_sha256_format"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_evidence_blobs_completed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_evidence_blobs_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_evidence_blobs_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_evidence_blobs_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_blobs")),
        schema="assets",
    )
    op.create_index(
        "ix_evidence_cooperative_status",
        "evidence_blobs",
        ["cooperative_id", "status"],
        unique=False,
        schema="assets",
    )
    op.create_table(
        "units_of_measure",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("symbol", sa.String(length=24), nullable=False),
        sa.Column("dimension", sa.String(length=40), nullable=False),
        sa.Column("decimal_scale", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE')", name=op.f("ck_units_of_measure_status_allowed")
        ),
        sa.CheckConstraint(
            "decimal_scale BETWEEN 0 AND 12", name=op.f("ck_units_of_measure_decimal_scale_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_units_of_measure_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_units_of_measure_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_units_of_measure_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units_of_measure")),
        sa.UniqueConstraint("cooperative_id", "code", name="uq_unit_cooperative_code"),
        schema="assets",
    )
    op.create_table(
        "warehouses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address_text", sa.String(length=500), nullable=False),
        sa.Column("storage_conditions", sa.String(length=500), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED','CLOSED')", name=op.f("ck_warehouses_status_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_warehouses_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_warehouses_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_warehouses_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("cooperative_id", "code", name="uq_warehouse_cooperative_code"),
        schema="assets",
    )
    op.create_index(
        "ix_warehouses_cooperative_status",
        "warehouses",
        ["cooperative_id", "status"],
        unique=False,
        schema="assets",
    )
    op.create_table(
        "evidence_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=80), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_evidence_links_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["assets.evidence_blobs.id"],
            name=op.f("fk_evidence_links_evidence_id_evidence_blobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_links")),
        sa.UniqueConstraint("evidence_id", "event_id", name="uq_evidence_link_event"),
        schema="assets",
    )
    op.create_index(
        "ix_evidence_links_subject",
        "evidence_links",
        ["subject_type", "subject_id"],
        unique=False,
        schema="assets",
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("default_unit_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity_tolerance",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "requires_evidence", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "shelf_life_required", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE')", name=op.f("ck_products_status_allowed")
        ),
        sa.CheckConstraint(
            "quantity_tolerance >= 0", name=op.f("ck_products_tolerance_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_products_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_products_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_products_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["default_unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_products_default_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("cooperative_id", "sku", name="uq_product_cooperative_sku"),
        schema="assets",
    )
    op.create_index(
        "ix_products_cooperative_status",
        "products",
        ["cooperative_id", "status"],
        unique=False,
        schema="assets",
    )
    op.create_table(
        "inventory_lots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("lot_number", sa.String(length=100), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("owner_member_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("declared_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("current_quantity", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("declared_quality", sa.String(length=200), nullable=False),
        sa.Column("verified_quality", sa.String(length=200), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storage_conditions", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("received_by_user_id", sa.UUID(), nullable=False),
        sa.Column("received_by_member_id", sa.UUID(), nullable=False),
        sa.Column("received_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("custodian_assignment_id", sa.UUID(), nullable=False),
        sa.Column("registered_event_id", sa.UUID(), nullable=False),
        sa.Column("verified_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING_VERIFICATION','VERIFIED','DISPUTED','FROZEN','LOST','DEPLETED')",
            name=op.f("ck_inventory_lots_status_allowed"),
        ),
        sa.CheckConstraint(
            "current_quantity IS NULL OR current_quantity >= 0",
            name=op.f("ck_inventory_lots_current_nonnegative"),
        ),
        sa.CheckConstraint(
            "declared_quantity > 0", name=op.f("ck_inventory_lots_declared_quantity_positive")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_inventory_lots_version_positive")),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_inventory_lots_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["custodian_assignment_id"],
            ["risk.responsibility_assignments.id"],
            name=op.f("fk_inventory_lots_custodian_assignment_id_responsibility_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_member_id"],
            ["identity.members.id"],
            name=op.f("fk_inventory_lots_owner_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["assets.products.id"],
            name=op.f("fk_inventory_lots_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_inventory_lots_received_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_inventory_lots_received_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_inventory_lots_received_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["registered_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_inventory_lots_registered_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_inventory_lots_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_inventory_lots_verified_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["assets.warehouses.id"],
            name=op.f("fk_inventory_lots_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_lots")),
        sa.UniqueConstraint("cooperative_id", "lot_number", name="uq_inventory_lot_number"),
        schema="assets",
    )
    op.create_index(
        "ix_inventory_lots_product_status",
        "inventory_lots",
        ["product_id", "status"],
        unique=False,
        schema="assets",
    )
    op.create_index(
        "ix_inventory_lots_warehouse_status",
        "inventory_lots",
        ["warehouse_id", "status"],
        unique=False,
        schema="assets",
    )
    op.create_table(
        "custody_transfers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("from_warehouse_id", sa.UUID(), nullable=False),
        sa.Column("to_warehouse_id", sa.UUID(), nullable=False),
        sa.Column("from_assignment_id", sa.UUID(), nullable=False),
        sa.Column("to_assignment_id", sa.UUID(), nullable=False),
        sa.Column("place", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("offered_by_user_id", sa.UUID(), nullable=False),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("offered_event_id", sa.UUID(), nullable=False),
        sa.Column("accepted_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "offered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('OFFERED','ACCEPTED','CANCELLED')",
            name=op.f("ck_custody_transfers_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_custody_transfers_accepted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_custody_transfers_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_assignment_id"],
            ["risk.responsibility_assignments.id"],
            name=op.f("fk_custody_transfers_from_assignment_id_responsibility_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_warehouse_id"],
            ["assets.warehouses.id"],
            name=op.f("fk_custody_transfers_from_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["assets.inventory_lots.id"],
            name=op.f("fk_custody_transfers_lot_id_inventory_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offered_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_custody_transfers_offered_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offered_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_custody_transfers_offered_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_assignment_id"],
            ["risk.responsibility_assignments.id"],
            name=op.f("fk_custody_transfers_to_assignment_id_responsibility_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_warehouse_id"],
            ["assets.warehouses.id"],
            name=op.f("fk_custody_transfers_to_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custody_transfers")),
        schema="assets",
    )
    op.create_index(
        "ix_custody_transfers_lot_status",
        "custody_transfers",
        ["lot_id", "status"],
        unique=False,
        schema="assets",
    )
    op.create_index(
        "uq_custody_transfer_open_lot",
        "custody_transfers",
        ["lot_id"],
        unique=True,
        schema="assets",
        postgresql_where=sa.text("status = 'OFFERED'"),
    )
    op.create_table(
        "inventory_discrepancies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("expected_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("actual_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("variance", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("recorded_by_user_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','RESOLVED','DISMISSED')",
            name=op.f("ck_inventory_discrepancies_status_allowed"),
        ),
        sa.CheckConstraint(
            "expected_quantity >= 0 AND actual_quantity >= 0",
            name=op.f("ck_inventory_discrepancies_quantities_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_inventory_discrepancies_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["assets.inventory_lots.id"],
            name=op.f("fk_inventory_discrepancies_lot_id_inventory_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_inventory_discrepancies_recorded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_discrepancies")),
        schema="assets",
    )
    op.create_index(
        "ix_inventory_discrepancies_lot_status",
        "inventory_discrepancies",
        ["lot_id", "status"],
        unique=False,
        schema="assets",
    )
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("movement_type", sa.String(length=32), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("resulting_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("performed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "movement_type IN ('ATTESTED_RECEIPT','DISCREPANCY_ADJUSTMENT')",
            name=op.f("ck_inventory_movements_type_allowed"),
        ),
        sa.CheckConstraint(
            "resulting_quantity >= 0", name=op.f("ck_inventory_movements_resulting_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_inventory_movements_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["assets.inventory_lots.id"],
            name=op.f("fk_inventory_movements_lot_id_inventory_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_inventory_movements_performed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
        sa.UniqueConstraint("event_id", name="uq_inventory_movement_event"),
        schema="assets",
    )
    op.create_index(
        "ix_inventory_movements_lot_created",
        "inventory_movements",
        ["lot_id", "created_at"],
        unique=False,
        schema="assets",
    )
    op.create_table(
        "stock_attestations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("measured_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("variance", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("quantity_decision", sa.String(length=24), nullable=False),
        sa.Column("quality_decision", sa.String(length=24), nullable=False),
        sa.Column("verified_quality", sa.String(length=200), nullable=False),
        sa.Column("measurements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=False),
        sa.Column("attested_by_user_id", sa.UUID(), nullable=False),
        sa.Column("attested_by_member_id", sa.UUID(), nullable=False),
        sa.Column("role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "attested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_decision IN ('ACCEPTED','CONDITIONAL','REJECTED')",
            name=op.f("ck_stock_attestations_quality_decision_allowed"),
        ),
        sa.CheckConstraint(
            "quantity_decision IN ('MATCH','WITHIN_TOLERANCE','DISCREPANCY')",
            name=op.f("ck_stock_attestations_quantity_decision_allowed"),
        ),
        sa.CheckConstraint(
            "measured_quantity >= 0", name=op.f("ck_stock_attestations_measured_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["attested_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_stock_attestations_attested_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["attested_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_stock_attestations_attested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_stock_attestations_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["assets.inventory_lots.id"],
            name=op.f("fk_stock_attestations_lot_id_inventory_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_stock_attestations_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_attestations")),
        sa.UniqueConstraint("lot_id", name="uq_stock_attestation_lot"),
        schema="assets",
    )
    op.create_table(
        "quality_inspections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("attestation_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("quality_grade", sa.String(length=200), nullable=False),
        sa.Column("measurements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('ACCEPTED','CONDITIONAL','REJECTED')",
            name=op.f("ck_quality_inspections_decision_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["attestation_id"],
            ["assets.stock_attestations.id"],
            name=op.f("fk_quality_inspections_attestation_id_stock_attestations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_quality_inspections_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["assets.inventory_lots.id"],
            name=op.f("fk_quality_inspections_lot_id_inventory_lots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_inspections")),
        sa.UniqueConstraint("attestation_id", name=op.f("uq_quality_inspections_attestation_id")),
        schema="assets",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION assets.prevent_inventory_evidence_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'inventory evidence record is append-only';
        END;
        $$;
        CREATE TRIGGER trg_evidence_links_append_only
          BEFORE UPDATE OR DELETE ON assets.evidence_links
          FOR EACH ROW EXECUTE FUNCTION assets.prevent_inventory_evidence_mutation();
        CREATE TRIGGER trg_stock_attestations_append_only
          BEFORE UPDATE OR DELETE ON assets.stock_attestations
          FOR EACH ROW EXECUTE FUNCTION assets.prevent_inventory_evidence_mutation();
        CREATE TRIGGER trg_quality_inspections_append_only
          BEFORE UPDATE OR DELETE ON assets.quality_inspections
          FOR EACH ROW EXECUTE FUNCTION assets.prevent_inventory_evidence_mutation();
        CREATE TRIGGER trg_inventory_movements_append_only
          BEFORE UPDATE OR DELETE ON assets.inventory_movements
          FOR EACH ROW EXECUTE FUNCTION assets.prevent_inventory_evidence_mutation();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION assets.protect_evidence_blob()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'evidence blob cannot be deleted';
          END IF;
          IF OLD.status <> 'PENDING' OR NEW.status NOT IN ('READY','FAILED') THEN
            RAISE EXCEPTION 'evidence blob transition is forbidden';
          END IF;
          IF NEW.id <> OLD.id
             OR NEW.cooperative_id <> OLD.cooperative_id
             OR NEW.expected_sha256 <> OLD.expected_sha256
             OR NEW.expected_size <> OLD.expected_size
             OR NEW.mime_type <> OLD.mime_type
             OR NEW.kind <> OLD.kind
             OR NEW.original_name <> OLD.original_name
             OR NEW.access_scope <> OLD.access_scope
             OR NEW.created_by_user_id <> OLD.created_by_user_id
             OR NEW.created_event_id <> OLD.created_event_id
             OR NEW.created_at <> OLD.created_at
             OR NEW.retention_until IS DISTINCT FROM OLD.retention_until THEN
            RAISE EXCEPTION 'evidence metadata is immutable';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_evidence_blobs_protected
          BEFORE UPDATE OR DELETE ON assets.evidence_blobs
          FOR EACH ROW EXECUTE FUNCTION assets.protect_evidence_blob();
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT USAGE ON SCHEMA assets TO coop_app;
            GRANT SELECT, INSERT ON assets.units_of_measure TO coop_app;
            GRANT SELECT, INSERT ON assets.products TO coop_app;
            GRANT SELECT, INSERT ON assets.warehouses TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON assets.evidence_blobs TO coop_app;
            GRANT SELECT, INSERT ON assets.evidence_links TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON assets.inventory_lots TO coop_app;
            GRANT SELECT, INSERT ON assets.stock_attestations TO coop_app;
            GRANT SELECT, INSERT ON assets.quality_inspections TO coop_app;
            GRANT SELECT, INSERT ON assets.inventory_movements TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON assets.inventory_discrepancies TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON assets.custody_transfers TO coop_app;
          END IF;
        END
        $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "ck_role_assignments_role_allowed",
        "role_assignments",
        schema="identity",
        type_="check",
    )
    op.create_check_constraint(
        "ck_role_assignments_role_allowed",
        "role_assignments",
        "role_code IN ('MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',"
        "'RISK_ADMIN','SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR')",
        schema="identity",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quality_inspections", schema="assets")
    op.drop_table("stock_attestations", schema="assets")
    op.drop_index(
        "ix_inventory_movements_lot_created", table_name="inventory_movements", schema="assets"
    )
    op.drop_table("inventory_movements", schema="assets")
    op.drop_index(
        "ix_inventory_discrepancies_lot_status",
        table_name="inventory_discrepancies",
        schema="assets",
    )
    op.drop_table("inventory_discrepancies", schema="assets")
    op.drop_index(
        "uq_custody_transfer_open_lot",
        table_name="custody_transfers",
        schema="assets",
        postgresql_where=sa.text("status = 'OFFERED'"),
    )
    op.drop_index(
        "ix_custody_transfers_lot_status", table_name="custody_transfers", schema="assets"
    )
    op.drop_table("custody_transfers", schema="assets")
    op.drop_index(
        "ix_inventory_lots_warehouse_status", table_name="inventory_lots", schema="assets"
    )
    op.drop_index("ix_inventory_lots_product_status", table_name="inventory_lots", schema="assets")
    op.drop_table("inventory_lots", schema="assets")
    op.drop_index("ix_products_cooperative_status", table_name="products", schema="assets")
    op.drop_table("products", schema="assets")
    op.drop_index("ix_evidence_links_subject", table_name="evidence_links", schema="assets")
    op.drop_table("evidence_links", schema="assets")
    op.drop_index("ix_warehouses_cooperative_status", table_name="warehouses", schema="assets")
    op.drop_table("warehouses", schema="assets")
    op.drop_table("units_of_measure", schema="assets")
    op.drop_index("ix_evidence_cooperative_status", table_name="evidence_blobs", schema="assets")
    op.drop_table("evidence_blobs", schema="assets")
    op.execute("DROP FUNCTION IF EXISTS assets.protect_evidence_blob")
    op.execute("DROP FUNCTION IF EXISTS assets.prevent_inventory_evidence_mutation")
    op.execute("DROP SCHEMA IF EXISTS assets")
    # ### end Alembic commands ###
