"""exchange vertical flow

Revision ID: 0006_exchange_vertical_flow
Revises: 0005_commodity_rights
Create Date: 2026-07-20 17:42:23.852286
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006_exchange_vertical_flow"
down_revision: str | None = "0005_commodity_rights"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS exchange")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("terms_version", sa.Integer(), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("confirmed_event_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PROPOSED','ACTIVE','PARTIALLY_FULFILLED','FULFILLED','DISPUTED','CANCELLED','DEFAULTED')",
            name=op.f("ck_deals_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_deals_terms_hash_sha256")
        ),
        sa.CheckConstraint(
            "terms_version >= 1 AND version >= 1", name=op.f("ck_deals_versions_positive")
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_deals_confirmed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_deals_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_deals_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_deals_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_deals_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_deals_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
        schema="exchange",
    )
    op.create_index(
        "ix_deals_cooperative_status",
        "deals",
        ["cooperative_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "deal_terms_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deal_id", sa.UUID(), nullable=False),
        sa.Column("terms_version", sa.Integer(), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_deal_terms_versions_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "terms_version >= 1", name=op.f("ck_deal_terms_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_deal_terms_versions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["exchange.deals.id"],
            name=op.f("fk_deal_terms_versions_deal_id_deals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_deal_terms_versions_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_terms_versions")),
        sa.UniqueConstraint(
            "deal_id", "terms_version", "terms_hash", name="uq_deal_terms_deal_version_hash"
        ),
        sa.UniqueConstraint("deal_id", "terms_version", name="uq_deal_terms_deal_version"),
        schema="exchange",
    )
    op.create_table(
        "deal_parties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deal_id", sa.UUID(), nullable=False),
        sa.Column("terms_version", sa.Integer(), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_deal_parties_terms_hash_sha256")
        ),
        sa.CheckConstraint("terms_version >= 1", name=op.f("ck_deal_parties_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_deal_parties_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id", "terms_version", "terms_hash"],
            [
                "exchange.deal_terms_versions.deal_id",
                "exchange.deal_terms_versions.terms_version",
                "exchange.deal_terms_versions.terms_hash",
            ],
            name="fk_deal_parties_terms_version_hash",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["exchange.deals.id"],
            name=op.f("fk_deal_parties_deal_id_deals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_deal_parties_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_parties")),
        sa.UniqueConstraint(
            "deal_id", "terms_version", "member_id", name="uq_deal_parties_deal_version_member"
        ),
        schema="exchange",
    )
    op.create_index(
        "ix_deal_parties_member_deal",
        "deal_parties",
        ["member_id", "deal_id"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "deal_confirmations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deal_id", sa.UUID(), nullable=False),
        sa.Column("terms_version", sa.Integer(), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("confirmed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_deal_confirmations_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "terms_version >= 1", name=op.f("ck_deal_confirmations_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_deal_confirmations_confirmed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id", "terms_version", "member_id"],
            [
                "exchange.deal_parties.deal_id",
                "exchange.deal_parties.terms_version",
                "exchange.deal_parties.member_id",
            ],
            name="fk_deal_confirmations_registered_party",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id", "terms_version", "terms_hash"],
            [
                "exchange.deal_terms_versions.deal_id",
                "exchange.deal_terms_versions.terms_version",
                "exchange.deal_terms_versions.terms_hash",
            ],
            name="fk_deal_confirmations_terms_version_hash",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["exchange.deals.id"],
            name=op.f("fk_deal_confirmations_deal_id_deals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_deal_confirmations_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_deal_confirmations_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_deal_confirmations_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_confirmations")),
        sa.UniqueConstraint(
            "deal_id", "terms_version", "member_id", name="uq_deal_confirmations_party_version"
        ),
        sa.UniqueConstraint("event_id", name=op.f("uq_deal_confirmations_event_id")),
        schema="exchange",
    )
    op.create_index(
        "ix_deal_confirmations_deal_version",
        "deal_confirmations",
        ["deal_id", "terms_version"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "obligations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deal_id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("terms_version", sa.Integer(), nullable=False),
        sa.Column("debtor_member_id", sa.UUID(), nullable=False),
        sa.Column("creditor_member_id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quality_criteria", sa.Text(), nullable=False),
        sa.Column("fulfillment_place", sa.String(length=500), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("quantity_total", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column(
            "quantity_submitted",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "quantity_fulfilled",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("partial_allowed", sa.Boolean(), nullable=False),
        sa.Column("evidence_required", sa.Boolean(), nullable=False),
        sa.Column("confirmation_method", sa.String(length=200), nullable=False),
        sa.Column("substitute_policy", sa.Text(), nullable=False),
        sa.Column("valuation_source", sa.String(length=300), nullable=False),
        sa.Column("liquidity_class", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("last_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE','PARTIALLY_FULFILLED','FULFILLED','OVERDUE','DISPUTED','DEFAULTED','CLOSED')",
            name=op.f("ck_obligations_status_allowed"),
        ),
        sa.CheckConstraint(
            "quantity_submitted >= 0 AND quantity_fulfilled >= 0 AND quantity_submitted + quantity_fulfilled <= quantity_total",
            name=op.f("ck_obligations_quantities_bounded"),
        ),
        sa.CheckConstraint("quantity_total > 0", name=op.f("ck_obligations_total_positive")),
        sa.CheckConstraint(
            "version >= 1 AND sequence_no >= 1", name=op.f("ck_obligations_versions_positive")
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_obligations_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_obligations_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creditor_member_id"],
            ["identity.members.id"],
            name=op.f("fk_obligations_creditor_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id", "terms_version", "creditor_member_id"],
            [
                "exchange.deal_parties.deal_id",
                "exchange.deal_parties.terms_version",
                "exchange.deal_parties.member_id",
            ],
            name="fk_obligations_creditor_party",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id", "terms_version", "debtor_member_id"],
            [
                "exchange.deal_parties.deal_id",
                "exchange.deal_parties.terms_version",
                "exchange.deal_parties.member_id",
            ],
            name="fk_obligations_debtor_party",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id", "terms_version"],
            ["exchange.deal_terms_versions.deal_id", "exchange.deal_terms_versions.terms_version"],
            name="fk_obligations_terms_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["exchange.deals.id"],
            name=op.f("fk_obligations_deal_id_deals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["debtor_member_id"],
            ["identity.members.id"],
            name=op.f("fk_obligations_debtor_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_obligations_last_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_obligations_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_obligations")),
        sa.UniqueConstraint("deal_id", "sequence_no", name="uq_obligations_deal_sequence"),
        schema="exchange",
    )
    op.create_index(
        "ix_obligations_creditor_status",
        "obligations",
        ["creditor_member_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.create_index(
        "ix_obligations_debtor_status_due",
        "obligations",
        ["debtor_member_id", "status", "due_at"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "logistics_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("obligation_id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("carrier_member_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("origin_text", sa.String(length=500), nullable=False),
        sa.Column("destination_text", sa.String(length=500), nullable=False),
        sa.Column("pickup_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("offered_by_user_id", sa.UUID(), nullable=False),
        sa.Column("offered_event_id", sa.UUID(), nullable=False),
        sa.Column("carrier_user_id", sa.UUID(), nullable=True),
        sa.Column("carrier_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("accepted_event_id", sa.UUID(), nullable=True),
        sa.Column("pickup_event_id", sa.UUID(), nullable=True),
        sa.Column("delivered_event_id", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('OFFERED','ACCEPTED','IN_TRANSIT','DELIVERED','CANCELLED','DISPUTED')",
            name=op.f("ck_logistics_orders_status_allowed"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_logistics_orders_quantity_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_logistics_orders_version_positive")),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_logistics_orders_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["carrier_member_id"],
            ["identity.members.id"],
            name=op.f("fk_logistics_orders_carrier_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["carrier_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_logistics_orders_carrier_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["carrier_user_id"],
            ["identity.users.id"],
            name=op.f("fk_logistics_orders_carrier_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_logistics_orders_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delivered_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_logistics_orders_delivered_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["exchange.obligations.id"],
            name=op.f("fk_logistics_orders_obligation_id_obligations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offered_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_logistics_orders_offered_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["offered_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_logistics_orders_offered_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pickup_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_logistics_orders_pickup_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_logistics_orders_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logistics_orders")),
        schema="exchange",
    )
    op.create_index(
        "ix_logistics_orders_carrier_status",
        "logistics_orders",
        ["carrier_member_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.create_index(
        "ix_logistics_orders_obligation_status",
        "logistics_orders",
        ["obligation_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "fulfillments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("obligation_id", sa.UUID(), nullable=False),
        sa.Column("logistics_order_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column(
            "accepted_quantity",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("quality_claim", sa.Text(), nullable=False),
        sa.Column("location_text", sa.String(length=500), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("performed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("performed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("submitted_event_id", sa.UUID(), nullable=False),
        sa.Column("accepted_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('SUBMITTED','ACCEPTED','PARTIALLY_ACCEPTED','REJECTED','DISPUTED')",
            name=op.f("ck_fulfillments_status_allowed"),
        ),
        sa.CheckConstraint(
            "accepted_quantity >= 0 AND accepted_quantity <= quantity",
            name=op.f("ck_fulfillments_accepted_bounded"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_fulfillments_quantity_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_fulfillments_version_positive")),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_fulfillments_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["logistics_order_id"],
            ["exchange.logistics_orders.id"],
            name=op.f("fk_fulfillments_logistics_order_id_logistics_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["exchange.obligations.id"],
            name=op.f("fk_fulfillments_obligation_id_obligations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_fulfillments_performed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_fulfillments_performed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_fulfillments_submitted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fulfillments")),
        schema="exchange",
    )
    op.create_index(
        "ix_fulfillments_obligation_status",
        "fulfillments",
        ["obligation_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "acceptance_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fulfillment_id", sa.UUID(), nullable=False),
        sa.Column("accepted_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("quality_status", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=False),
        sa.Column("accepted_by_member_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('ACCEPTED','PARTIALLY_ACCEPTED','REJECTED')",
            name=op.f("ck_acceptance_records_decision_allowed"),
        ),
        sa.CheckConstraint(
            "accepted_quantity >= 0", name=op.f("ck_acceptance_records_quantity_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_acceptance_records_accepted_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_acceptance_records_accepted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_acceptance_records_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fulfillment_id"],
            ["exchange.fulfillments.id"],
            name=op.f("fk_acceptance_records_fulfillment_id_fulfillments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acceptance_records")),
        sa.UniqueConstraint("event_id", name=op.f("uq_acceptance_records_event_id")),
        sa.UniqueConstraint("fulfillment_id", name="uq_acceptance_fulfillment"),
        schema="exchange",
    )
    op.create_table(
        "obligation_disputes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("obligation_id", sa.UUID(), nullable=False),
        sa.Column("fulfillment_id", sa.UUID(), nullable=True),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column("opened_by_member_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','RESOLVED','REJECTED')",
            name=op.f("ck_obligation_disputes_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_obligation_disputes_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fulfillment_id"],
            ["exchange.fulfillments.id"],
            name=op.f("fk_obligation_disputes_fulfillment_id_fulfillments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["exchange.obligations.id"],
            name=op.f("fk_obligation_disputes_obligation_id_obligations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_obligation_disputes_opened_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_obligation_disputes_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_obligation_disputes")),
        sa.UniqueConstraint("event_id", name=op.f("uq_obligation_disputes_event_id")),
        schema="exchange",
    )
    op.create_index(
        "ix_obligation_disputes_obligation_status",
        "obligation_disputes",
        ["obligation_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT USAGE ON SCHEMA exchange TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA exchange TO coop_app;
            ALTER DEFAULT PRIVILEGES IN SCHEMA exchange
              GRANT SELECT, INSERT, UPDATE ON TABLES TO coop_app;
          END IF;
        END $$;
        """
    )  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_obligation_disputes_obligation_status",
        table_name="obligation_disputes",
        schema="exchange",
    )
    op.drop_table("obligation_disputes", schema="exchange")
    op.drop_table("acceptance_records", schema="exchange")
    op.drop_index("ix_fulfillments_obligation_status", table_name="fulfillments", schema="exchange")
    op.drop_table("fulfillments", schema="exchange")
    op.drop_index(
        "ix_logistics_orders_obligation_status", table_name="logistics_orders", schema="exchange"
    )
    op.drop_index(
        "ix_logistics_orders_carrier_status", table_name="logistics_orders", schema="exchange"
    )
    op.drop_table("logistics_orders", schema="exchange")
    op.drop_index("ix_obligations_debtor_status_due", table_name="obligations", schema="exchange")
    op.drop_index("ix_obligations_creditor_status", table_name="obligations", schema="exchange")
    op.drop_table("obligations", schema="exchange")
    op.drop_index(
        "ix_deal_confirmations_deal_version", table_name="deal_confirmations", schema="exchange"
    )
    op.drop_table("deal_confirmations", schema="exchange")
    op.drop_index("ix_deal_parties_member_deal", table_name="deal_parties", schema="exchange")
    op.drop_table("deal_parties", schema="exchange")
    op.drop_table("deal_terms_versions", schema="exchange")
    op.drop_index("ix_deals_cooperative_status", table_name="deals", schema="exchange")
    op.drop_table("deals", schema="exchange")
    op.execute("DROP SCHEMA IF EXISTS exchange")
    # ### end Alembic commands ###
