"""bounded risk vertical flow

Revision ID: 0008_bounded_risk_vertical_flow
Revises: 0007_exchange_dispute_resolution
Create Date: 2026-07-20 20:04:00.257591
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008_bounded_risk_vertical_flow"
down_revision: str | None = "0007_exchange_dispute_resolution"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS risk")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "related_party_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("member_a_id", sa.UUID(), nullable=False),
        sa.Column("member_b_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.String(length=24), nullable=False),
        sa.Column("source_statement", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("decided_by_member_id", sa.UUID(), nullable=True),
        sa.Column("decision_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('HOUSEHOLD','CONTROL','RELATED')",
            name=op.f("ck_related_party_links_relation_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_APPROVAL','ACTIVE','REJECTED','ENDED')",
            name=op.f("ck_related_party_links_status_allowed"),
        ),
        sa.CheckConstraint(
            "member_a_id < member_b_id",
            name=op.f("ck_related_party_links_members_ordered_distinct"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_related_party_links_version_positive")),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_related_party_links_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_related_party_links_decided_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_related_party_links_decided_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decision_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_related_party_links_decision_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_a_id"],
            ["identity.members.id"],
            name=op.f("fk_related_party_links_member_a_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_b_id"],
            ["identity.members.id"],
            name=op.f("fk_related_party_links_member_b_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_related_party_links_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_related_party_links_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_related_party_links_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_related_party_links")),
        sa.UniqueConstraint(
            "decision_event_id", name=op.f("uq_related_party_links_decision_event_id")
        ),
        sa.UniqueConstraint(
            "proposed_event_id", name=op.f("uq_related_party_links_proposed_event_id")
        ),
        schema="risk",
    )
    op.create_index(
        "ix_related_party_links_member_a_status",
        "related_party_links",
        ["member_a_id", "status"],
        unique=False,
        schema="risk",
    )
    op.create_index(
        "ix_related_party_links_member_b_status",
        "related_party_links",
        ["member_b_id", "status"],
        unique=False,
        schema="risk",
    )
    op.create_index(
        "uq_related_party_links_open_pair",
        "related_party_links",
        ["cooperative_id", "member_a_id", "member_b_id"],
        unique=True,
        schema="risk",
        postgresql_where=sa.text("status IN ('PENDING_APPROVAL','ACTIVE')"),
    )
    op.create_table(
        "risk_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("denomination", sa.String(length=32), nullable=False),
        sa.Column("max_member_exposure", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_related_exposure", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_guarantee_chain_depth", sa.Integer(), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("approved_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'PROPOSED' AND approved_event_id IS NULL AND approved_at IS NULL) OR (status IN ('ACTIVE','SUPERSEDED') AND approved_event_id IS NOT NULL AND approved_at IS NOT NULL) OR status = 'REJECTED'",
            name=op.f("ck_risk_policies_approval_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','ACTIVE','REJECTED','SUPERSEDED')",
            name=op.f("ck_risk_policies_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_risk_policies_terms_hash_sha256")
        ),
        sa.CheckConstraint(
            "max_guarantee_chain_depth BETWEEN 1 AND 20",
            name=op.f("ck_risk_policies_chain_depth_bounded"),
        ),
        sa.CheckConstraint(
            "max_member_exposure > 0 AND max_related_exposure > 0 AND max_related_exposure >= max_member_exposure",
            name=op.f("ck_risk_policies_limits_positive"),
        ),
        sa.CheckConstraint(
            "policy_version >= 1 AND version >= 1", name=op.f("ck_risk_policies_versions_positive")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_risk_policies_approved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_risk_policies_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_risk_policies_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_risk_policies_approved_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_risk_policies_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_risk_policies_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_risk_policies_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_risk_policies_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_risk_policies_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_policies")),
        sa.UniqueConstraint("approved_event_id", name=op.f("uq_risk_policies_approved_event_id")),
        sa.UniqueConstraint(
            "cooperative_id", "policy_version", name="uq_risk_policies_cooperative_version"
        ),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_risk_policies_proposed_event_id")),
        schema="risk",
    )
    op.create_index(
        "uq_risk_policies_active_denomination",
        "risk_policies",
        ["cooperative_id", "denomination"],
        unique=True,
        schema="risk",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "share_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("opening_policy_id", sa.UUID(), nullable=False),
        sa.Column("contour", sa.String(length=24), nullable=False),
        sa.Column("denomination", sa.String(length=32), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "protected_amount",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "executed_not_settled",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("last_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "contour IN ('PRIMARY','GUARANTEE','ROLE','INFRASTRUCTURE','SOLIDARITY')",
            name=op.f("ck_share_accounts_contour_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','FROZEN','CLOSED')", name=op.f("ck_share_accounts_status_allowed")
        ),
        sa.CheckConstraint(
            "balance >= 0 AND protected_amount >= 0 AND executed_not_settled >= 0 AND protected_amount + executed_not_settled <= balance",
            name=op.f("ck_share_accounts_amounts_bounded"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_share_accounts_version_positive")),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_share_accounts_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_share_accounts_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_share_accounts_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_share_accounts_last_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_share_accounts_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opening_policy_id"],
            ["risk.risk_policies.id"],
            name=op.f("fk_share_accounts_opening_policy_id_risk_policies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_accounts")),
        sa.UniqueConstraint(
            "cooperative_id",
            "member_id",
            "contour",
            "denomination",
            name="uq_share_accounts_member_contour_denomination",
        ),
        sa.UniqueConstraint("created_event_id", name=op.f("uq_share_accounts_created_event_id")),
        schema="risk",
    )
    op.create_index(
        "ix_share_accounts_member_status",
        "share_accounts",
        ["member_id", "status"],
        unique=False,
        schema="risk",
    )
    op.create_table(
        "exposure_commitments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("owner_member_id", sa.UUID(), nullable=False),
        sa.Column("commitment_type", sa.String(length=32), nullable=False),
        sa.Column("risk_type", sa.String(length=64), nullable=False),
        sa.Column("risk_id", sa.UUID(), nullable=False),
        sa.Column("debtor_member_id", sa.UUID(), nullable=True),
        sa.Column("beneficiary_member_id", sa.UUID(), nullable=True),
        sa.Column("role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("amount_reserved", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_loss", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("coverage_ratio", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("release_condition", sa.Text(), nullable=False),
        sa.Column("trigger_conditions", sa.Text(), nullable=False),
        sa.Column("exclusions", sa.Text(), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("accepted_event_id", sa.UUID(), nullable=True),
        sa.Column("released_by_user_id", sa.UUID(), nullable=True),
        sa.Column("released_event_id", sa.UUID(), nullable=True),
        sa.Column("release_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(commitment_type = 'GUARANTEE' AND debtor_member_id IS NOT NULL AND beneficiary_member_id IS NOT NULL) OR commitment_type <> 'GUARANTEE'",
            name=op.f("ck_exposure_commitments_guarantee_parties_present"),
        ),
        sa.CheckConstraint(
            "(commitment_type = 'ROLE_BOND' AND role_assignment_id IS NOT NULL) OR commitment_type <> 'ROLE_BOND'",
            name=op.f("ck_exposure_commitments_role_bond_assignment_present"),
        ),
        sa.CheckConstraint(
            "(status = 'PROPOSED' AND accepted_event_id IS NULL AND released_event_id IS NULL) OR (status = 'ACTIVE' AND accepted_event_id IS NOT NULL AND released_event_id IS NULL) OR (status IN ('RELEASED','CANCELLED') AND released_event_id IS NOT NULL)",
            name=op.f("ck_exposure_commitments_lifecycle_consistent"),
        ),
        sa.CheckConstraint(
            "commitment_type IN ('DIRECT_OBLIGATION','GUARANTEE','CREDIT_LIMIT','ROLE_BOND')",
            name=op.f("ck_exposure_commitments_type_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','ACTIVE','RELEASED','CANCELLED')",
            name=op.f("ck_exposure_commitments_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_exposure_commitments_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "amount_reserved > 0 AND max_loss > 0 AND max_loss <= amount_reserved",
            name=op.f("ck_exposure_commitments_amounts_bounded"),
        ),
        sa.CheckConstraint(
            "coverage_ratio > 0 AND coverage_ratio <= 1",
            name=op.f("ck_exposure_commitments_ratio_bounded"),
        ),
        sa.CheckConstraint(
            "starts_at < expires_at", name=op.f("ck_exposure_commitments_period_valid")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_exposure_commitments_version_positive")),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_exposure_commitments_accepted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_exposure_commitments_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_exposure_commitments_accepted_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["risk.share_accounts.id"],
            name=op.f("fk_exposure_commitments_account_id_share_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_member_id"],
            ["identity.members.id"],
            name=op.f("fk_exposure_commitments_beneficiary_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_exposure_commitments_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["debtor_member_id"],
            ["identity.members.id"],
            name=op.f("fk_exposure_commitments_debtor_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_member_id"],
            ["identity.members.id"],
            name=op.f("fk_exposure_commitments_owner_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["risk.risk_policies.id"],
            name=op.f("fk_exposure_commitments_policy_id_risk_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_exposure_commitments_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_exposure_commitments_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_exposure_commitments_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_exposure_commitments_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["released_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_exposure_commitments_released_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["released_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_exposure_commitments_released_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_exposure_commitments_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exposure_commitments")),
        sa.UniqueConstraint(
            "accepted_event_id", name=op.f("uq_exposure_commitments_accepted_event_id")
        ),
        sa.UniqueConstraint(
            "proposed_event_id", name=op.f("uq_exposure_commitments_proposed_event_id")
        ),
        sa.UniqueConstraint(
            "released_event_id", name=op.f("uq_exposure_commitments_released_event_id")
        ),
        schema="risk",
    )
    op.create_index(
        "ix_exposure_commitments_owner_status",
        "exposure_commitments",
        ["owner_member_id", "status"],
        unique=False,
        schema="risk",
    )
    op.create_index(
        "ix_exposure_commitments_subject_status",
        "exposure_commitments",
        ["risk_id", "status"],
        unique=False,
        schema="risk",
    )
    op.create_index(
        "uq_exposure_commitments_active_risk_account",
        "exposure_commitments",
        ["account_id", "risk_type", "risk_id"],
        unique=True,
        schema="risk",
        postgresql_where=sa.text("status IN ('PROPOSED','ACTIVE')"),
    )
    op.create_table(
        "share_contributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("entry_type", sa.String(length=24), nullable=False),
        sa.Column("source_reference", sa.String(length=300), nullable=False),
        sa.Column("recorded_by_user_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entry_type = 'CONTRIBUTION'", name=op.f("ck_share_contributions_entry_type_allowed")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_share_contributions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["risk.share_accounts.id"],
            name=op.f("fk_share_contributions_account_id_share_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_share_contributions_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_share_contributions_recorded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_contributions")),
        sa.UniqueConstraint("event_id", name=op.f("uq_share_contributions_event_id")),
        schema="risk",
    )
    op.create_index(
        "ix_share_contributions_account_created",
        "share_contributions",
        ["account_id", "created_at"],
        unique=False,
        schema="risk",
    )
    op.create_table(
        "liability_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("commitment_id", sa.UUID(), nullable=False),
        sa.Column("incident_reference", sa.String(length=80), nullable=False),
        sa.Column("responsible_member_id", sa.UUID(), nullable=False),
        sa.Column("affected_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("facts", sa.Text(), nullable=False),
        sa.Column("causal_graph", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column("opened_by_member_id", sa.UUID(), nullable=False),
        sa.Column("opened_event_id", sa.UUID(), nullable=False),
        sa.Column("fault_class", sa.String(length=32), nullable=True),
        sa.Column("assessed_loss", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("coverage_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assessment_rationale", sa.Text(), nullable=True),
        sa.Column("assessed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("assessed_by_member_id", sa.UUID(), nullable=True),
        sa.Column("assessed_event_id", sa.UUID(), nullable=True),
        sa.Column("appeal_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'OPEN' AND assessed_event_id IS NULL AND assessed_loss IS NULL) OR (status IN ('ASSESSED','CLOSED') AND assessed_event_id IS NOT NULL AND assessed_loss IS NOT NULL AND fault_class IS NOT NULL)",
            name=op.f("ck_liability_cases_assessment_consistent"),
        ),
        sa.CheckConstraint(
            "fault_class IS NULL OR fault_class IN ('FORCE_MAJEURE','GOOD_FAITH_ERROR','NEGLIGENCE','GROSS_NEGLIGENCE','INTENT','COLLUSION')",
            name=op.f("ck_liability_cases_fault_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','ASSESSED','CLOSED')", name=op.f("ck_liability_cases_status_allowed")
        ),
        sa.CheckConstraint(
            "affected_amount > 0", name=op.f("ck_liability_cases_affected_positive")
        ),
        sa.CheckConstraint(
            "assessed_loss IS NULL OR assessed_loss >= 0",
            name=op.f("ck_liability_cases_loss_nonnegative"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_liability_cases_version_positive")),
        sa.ForeignKeyConstraint(
            ["assessed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_liability_cases_assessed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assessed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_liability_cases_assessed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assessed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_liability_cases_assessed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["commitment_id"],
            ["risk.exposure_commitments.id"],
            name=op.f("fk_liability_cases_commitment_id_exposure_commitments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_liability_cases_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_liability_cases_opened_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_liability_cases_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_liability_cases_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_member_id"],
            ["identity.members.id"],
            name=op.f("fk_liability_cases_responsible_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_liability_cases")),
        sa.UniqueConstraint(
            "cooperative_id",
            "incident_reference",
            name="uq_liability_cases_cooperative_incident",
        ),
        sa.UniqueConstraint("assessed_event_id", name=op.f("uq_liability_cases_assessed_event_id")),
        sa.UniqueConstraint("opened_event_id", name=op.f("uq_liability_cases_opened_event_id")),
        schema="risk",
    )
    op.create_index(
        "ix_liability_cases_responsible_status",
        "liability_cases",
        ["responsible_member_id", "status"],
        unique=False,
        schema="risk",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION risk.prevent_share_contribution_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'share contribution history is append-only';
        END;
        $$;
        CREATE TRIGGER trg_share_contributions_append_only
          BEFORE UPDATE OR DELETE ON risk.share_contributions
          FOR EACH ROW EXECUTE FUNCTION risk.prevent_share_contribution_mutation();
        """
    )
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT USAGE ON SCHEMA risk TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA risk TO coop_app;
            REVOKE UPDATE, DELETE ON risk.share_contributions FROM coop_app;
            ALTER DEFAULT PRIVILEGES IN SCHEMA risk
              GRANT SELECT, INSERT, UPDATE ON TABLES TO coop_app;
          END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM risk.risk_policies)
             OR EXISTS (SELECT 1 FROM risk.share_accounts)
             OR EXISTS (SELECT 1 FROM risk.related_party_links)
             OR EXISTS (SELECT 1 FROM risk.exposure_commitments)
             OR EXISTS (SELECT 1 FROM risk.share_contributions)
             OR EXISTS (SELECT 1 FROM risk.liability_cases) THEN
            RAISE EXCEPTION 'cannot downgrade 0008: bounded-risk records would be lost';
          END IF;
        END
        $$;
        """
    )
    op.execute("DROP FUNCTION IF EXISTS risk.prevent_share_contribution_mutation CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_liability_cases_responsible_status", table_name="liability_cases", schema="risk"
    )
    op.drop_table("liability_cases", schema="risk")
    op.drop_index(
        "ix_share_contributions_account_created", table_name="share_contributions", schema="risk"
    )
    op.drop_table("share_contributions", schema="risk")
    op.drop_index(
        "uq_exposure_commitments_active_risk_account",
        table_name="exposure_commitments",
        schema="risk",
        postgresql_where=sa.text("status IN ('PROPOSED','ACTIVE')"),
    )
    op.drop_index(
        "ix_exposure_commitments_subject_status", table_name="exposure_commitments", schema="risk"
    )
    op.drop_index(
        "ix_exposure_commitments_owner_status", table_name="exposure_commitments", schema="risk"
    )
    op.drop_table("exposure_commitments", schema="risk")
    op.drop_index("ix_share_accounts_member_status", table_name="share_accounts", schema="risk")
    op.drop_table("share_accounts", schema="risk")
    op.drop_index(
        "uq_risk_policies_active_denomination",
        table_name="risk_policies",
        schema="risk",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("risk_policies", schema="risk")
    op.drop_index(
        "uq_related_party_links_open_pair",
        table_name="related_party_links",
        schema="risk",
        postgresql_where=sa.text("status IN ('PENDING_APPROVAL','ACTIVE')"),
    )
    op.drop_index(
        "ix_related_party_links_member_b_status", table_name="related_party_links", schema="risk"
    )
    op.drop_index(
        "ix_related_party_links_member_a_status", table_name="related_party_links", schema="risk"
    )
    op.drop_table("related_party_links", schema="risk")
    # ### end Alembic commands ###
