"""local clearing vertical flow

Revision ID: 0009_local_clearing
Revises: 0008_bounded_risk_vertical_flow
Create Date: 2026-07-20 22:10:10.896020
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009_local_clearing"
down_revision: str | None = "0008_bounded_risk_vertical_flow"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR'
            )
          );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clearing_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("valuation_unit_id", sa.UUID(), nullable=False),
        sa.Column("algorithm_id", sa.String(length=32), nullable=False),
        sa.Column("algorithm_version", sa.String(length=16), nullable=False),
        sa.Column("decimal_scale", sa.Integer(), nullable=False),
        sa.Column("rounding_mode", sa.String(length=16), nullable=False),
        sa.Column("minimum_operation", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_iterations", sa.Integer(), nullable=False),
        sa.Column("max_cycle_length", sa.Integer(), nullable=False),
        sa.Column("dispute_window_seconds", sa.Integer(), nullable=False),
        sa.Column("required_approvals", sa.Integer(), nullable=False),
        sa.Column("liquidity_order", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("approved_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "algorithm_id = 'LOCAL_NETTING'", name=op.f("ck_clearing_policies_algorithm_allowed")
        ),
        sa.CheckConstraint(
            "algorithm_version = '1.0.0'",
            name=op.f("ck_clearing_policies_algorithm_version_allowed"),
        ),
        sa.CheckConstraint(
            "rounding_mode IN ('DOWN','HALF_EVEN')",
            name=op.f("ck_clearing_policies_rounding_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','ACTIVE','REJECTED','SUPERSEDED')",
            name=op.f("ck_clearing_policies_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_clearing_policies_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "decimal_scale BETWEEN 0 AND 12",
            name=op.f("ck_clearing_policies_decimal_scale_allowed"),
        ),
        sa.CheckConstraint(
            "dispute_window_seconds BETWEEN 0 AND 2592000",
            name=op.f("ck_clearing_policies_dispute_window_bounded"),
        ),
        sa.CheckConstraint(
            "max_cycle_length BETWEEN 3 AND 12",
            name=op.f("ck_clearing_policies_cycle_length_bounded"),
        ),
        sa.CheckConstraint(
            "max_iterations BETWEEN 1 AND 100000",
            name=op.f("ck_clearing_policies_iterations_bounded"),
        ),
        sa.CheckConstraint(
            "minimum_operation >= 0", name=op.f("ck_clearing_policies_minimum_nonnegative")
        ),
        sa.CheckConstraint(
            "policy_version >= 1 AND version >= 1",
            name=op.f("ck_clearing_policies_versions_positive"),
        ),
        sa.CheckConstraint(
            "required_approvals BETWEEN 1 AND 3",
            name=op.f("ck_clearing_policies_approvals_bounded"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_policies_approved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_policies_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_policies_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_clearing_policies_approved_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_clearing_policies_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_policies_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_policies_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_policies_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_clearing_policies_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["valuation_unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_clearing_policies_valuation_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_policies")),
        sa.UniqueConstraint(
            "approved_event_id", name=op.f("uq_clearing_policies_approved_event_id")
        ),
        sa.UniqueConstraint(
            "cooperative_id", "policy_version", name="uq_clearing_policy_cooperative_version"
        ),
        sa.UniqueConstraint(
            "proposed_event_id", name=op.f("uq_clearing_policies_proposed_event_id")
        ),
        schema="exchange",
    )
    op.create_index(
        "ix_clearing_policies_cooperative_status",
        "clearing_policies",
        ["cooperative_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.create_index(
        "uq_clearing_policy_active",
        "clearing_policies",
        ["cooperative_id"],
        unique=True,
        schema="exchange",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "clearing_cycles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("cycle_code", sa.String(length=80), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("collected_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=True),
        sa.Column("parameters_hash", sa.String(length=71), nullable=True),
        sa.Column("result_hash", sa.String(length=71), nullable=True),
        sa.Column("dispute_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_member_id", sa.UUID(), nullable=False),
        sa.Column("created_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("collection_event_id", sa.UUID(), nullable=True),
        sa.Column("freeze_event_id", sa.UUID(), nullable=True),
        sa.Column("preview_event_id", sa.UUID(), nullable=True),
        sa.Column("ready_event_id", sa.UUID(), nullable=True),
        sa.Column("finalized_event_id", sa.UUID(), nullable=True),
        sa.Column("reconciled_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("previewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','COLLECTING','INPUT_FROZEN','PREVIEWED','DISPUTE_WINDOW','DISPUTED','READY_TO_FINALIZE','FINALIZED','RECONCILED','CANCELLED','FAILED_FINALIZATION','SUPERSEDED')",
            name=op.f("ck_clearing_cycles_status_allowed"),
        ),
        sa.CheckConstraint(
            "period_end > period_start", name=op.f("ck_clearing_cycles_period_ordered")
        ),
        sa.CheckConstraint(
            "version >= 1 AND collected_count >= 0",
            name=op.f("ck_clearing_cycles_version_count_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_cycles_collection_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_clearing_cycles_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_cycles_created_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_cycles_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_cycles_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_clearing_cycles_created_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finalized_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_cycles_finalized_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["freeze_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_cycles_freeze_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["exchange.clearing_policies.id"],
            name=op.f("fk_clearing_cycles_policy_id_clearing_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["preview_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_cycles_preview_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ready_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_cycles_ready_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reconciled_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_cycles_reconciled_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_cycles")),
        sa.UniqueConstraint("cooperative_id", "cycle_code", name="uq_clearing_cycle_code"),
        schema="exchange",
    )
    op.create_index(
        "ix_clearing_cycles_cooperative_status",
        "clearing_cycles",
        ["cooperative_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.create_index(
        "ix_clearing_cycles_period",
        "clearing_cycles",
        ["period_start", "period_end"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "clearing_accounting_exports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("export_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("package_hash", sa.String(length=71), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "package_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_clearing_accounting_exports_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_accounting_exports_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_accounting_exports_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_accounting_exports_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_accounting_exports")),
        sa.UniqueConstraint("cycle_id", name="uq_clearing_accounting_export_cycle"),
        schema="exchange",
    )
    op.create_table(
        "clearing_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("approval_type", sa.String(length=24), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("result_hash", sa.String(length=71), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "approval_type = 'CONTROLLER'", name=op.f("ck_clearing_approvals_type_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_approvals_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_approvals_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_approvals_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_clearing_approvals_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_approvals_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_approvals")),
        sa.UniqueConstraint("cycle_id", "member_id", name="uq_clearing_approval_member"),
        sa.UniqueConstraint("event_id", name="uq_clearing_approval_event"),
        schema="exchange",
    )
    op.create_table(
        "clearing_input_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("input_version", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("ordered_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("frozen_by_user_id", sa.UUID(), nullable=False),
        sa.Column("frozen_by_member_id", sa.UUID(), nullable=False),
        sa.Column("frozen_event_id", sa.UUID(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_clearing_input_snapshots_input_hash_sha256"),
        ),
        sa.CheckConstraint(
            "input_version >= 1", name=op.f("ck_clearing_input_snapshots_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_input_snapshots_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["frozen_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_input_snapshots_frozen_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["frozen_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_input_snapshots_frozen_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["frozen_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_input_snapshots_frozen_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_input_snapshots")),
        sa.UniqueConstraint("cycle_id", "input_version", name="uq_clearing_snapshot_cycle_version"),
        sa.UniqueConstraint("cycle_id", name="uq_clearing_snapshot_cycle"),
        sa.UniqueConstraint(
            "frozen_event_id", name=op.f("uq_clearing_input_snapshots_frozen_event_id")
        ),
        schema="exchange",
    )
    op.create_table(
        "clearing_positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("incoming_before", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("outgoing_before", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("incoming_cleared", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("outgoing_cleared", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("incoming_after", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("outgoing_after", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("net_before", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("net_after", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "incoming_before >= 0 AND outgoing_before >= 0 AND incoming_cleared >= 0 AND outgoing_cleared >= 0 AND incoming_after >= 0 AND outgoing_after >= 0",
            name=op.f("ck_clearing_positions_amounts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_positions_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_positions_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_clearing_positions_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_positions")),
        sa.UniqueConstraint("cycle_id", "member_id", "unit_id", name="uq_clearing_position"),
        schema="exchange",
    )
    op.create_table(
        "clearing_proofs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("proof_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proof_hash", sa.String(length=71), nullable=False),
        sa.Column("finalized_event_id", sa.UUID(), nullable=False),
        sa.Column("node_event_hash", sa.String(length=71), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "proof_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_clearing_proofs_proof_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_proofs_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finalized_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_proofs_finalized_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_proofs")),
        sa.UniqueConstraint("cycle_id", name="uq_clearing_proof_cycle"),
        sa.UniqueConstraint("finalized_event_id", name="uq_clearing_proof_event"),
        schema="exchange",
    )
    op.create_table(
        "clearing_statements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("statement_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("statement_hash", sa.String(length=71), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statement_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_clearing_statements_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_statements_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_statements_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_statements_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_clearing_statements_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_statements")),
        sa.UniqueConstraint("cycle_id", "member_id", "unit_id", name="uq_clearing_statement"),
        schema="exchange",
    )
    op.create_table(
        "clearing_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("obligation_id", sa.UUID(), nullable=False),
        sa.Column("debtor_member_id", sa.UUID(), nullable=False),
        sa.Column("creditor_member_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("obligation_version", sa.Integer(), nullable=False),
        sa.Column("amount_before", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("cleared_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("amount_after", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("inclusion_status", sa.String(length=16), nullable=False),
        sa.Column("exclusion_reason", sa.String(length=80), nullable=True),
        sa.Column("allocations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "inclusion_status IN ('INCLUDED','EXCLUDED')",
            name=op.f("ck_clearing_entries_inclusion_status_allowed"),
        ),
        sa.CheckConstraint(
            "amount_before > 0 AND cleared_amount >= 0 AND amount_after >= 0 AND cleared_amount <= amount_before AND amount_after = amount_before - cleared_amount",
            name=op.f("ck_clearing_entries_amounts_bounded"),
        ),
        sa.CheckConstraint(
            "obligation_version >= 1", name=op.f("ck_clearing_entries_obligation_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["creditor_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_entries_creditor_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_entries_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["debtor_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_entries_debtor_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["exchange.obligations.id"],
            name=op.f("fk_clearing_entries_obligation_id_obligations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["assets.units_of_measure.id"],
            name=op.f("fk_clearing_entries_unit_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_entries")),
        sa.UniqueConstraint("cycle_id", "obligation_id", name="uq_clearing_entry_obligation"),
        schema="exchange",
    )
    op.create_index(
        "ix_clearing_entries_cycle_creditor",
        "clearing_entries",
        ["cycle_id", "creditor_member_id"],
        unique=False,
        schema="exchange",
    )
    op.create_index(
        "ix_clearing_entries_cycle_member",
        "clearing_entries",
        ["cycle_id", "debtor_member_id"],
        unique=False,
        schema="exchange",
    )
    op.create_table(
        "clearing_disputes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column("opened_by_member_id", sa.UUID(), nullable=False),
        sa.Column("opened_event_id", sa.UUID(), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("resolution_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN','UPHELD','REJECTED')",
            name=op.f("ck_clearing_disputes_status_allowed"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_clearing_disputes_version_positive")),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["exchange.clearing_cycles.id"],
            name=op.f("fk_clearing_disputes_cycle_id_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["exchange.clearing_entries.id"],
            name=op.f("fk_clearing_disputes_entry_id_clearing_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_disputes_opened_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_disputes_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_disputes_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolution_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_clearing_disputes_resolution_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_clearing_disputes_resolved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_clearing_disputes_resolved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clearing_disputes")),
        schema="exchange",
    )
    op.create_index(
        "ix_clearing_disputes_cycle_status",
        "clearing_disputes",
        ["cycle_id", "status"],
        unique=False,
        schema="exchange",
    )
    op.add_column(
        "obligations",
        sa.Column(
            "quantity_cleared",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        schema="exchange",
    )
    op.add_column(
        "obligations",
        sa.Column(
            "clearing_allowed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        schema="exchange",
    )
    op.execute(
        """
        ALTER TABLE exchange.obligations
          DROP CONSTRAINT ck_obligations_quantities_bounded;
        ALTER TABLE exchange.obligations
          ADD CONSTRAINT ck_obligations_quantities_bounded CHECK (
            quantity_submitted >= 0
            AND quantity_fulfilled >= 0
            AND quantity_cleared >= 0
            AND quantity_submitted + quantity_fulfilled + quantity_cleared <= quantity_total
          );
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION exchange.prevent_clearing_proof_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'clearing proof records are append-only';
        END;
        $$;
        CREATE TRIGGER trg_clearing_snapshots_append_only
          BEFORE UPDATE OR DELETE ON exchange.clearing_input_snapshots
          FOR EACH ROW EXECUTE FUNCTION exchange.prevent_clearing_proof_mutation();
        CREATE TRIGGER trg_clearing_entries_append_only
          BEFORE UPDATE OR DELETE ON exchange.clearing_entries
          FOR EACH ROW EXECUTE FUNCTION exchange.prevent_clearing_proof_mutation();
        CREATE TRIGGER trg_clearing_positions_append_only
          BEFORE UPDATE OR DELETE ON exchange.clearing_positions
          FOR EACH ROW EXECUTE FUNCTION exchange.prevent_clearing_proof_mutation();
        CREATE TRIGGER trg_clearing_approvals_append_only
          BEFORE UPDATE OR DELETE ON exchange.clearing_approvals
          FOR EACH ROW EXECUTE FUNCTION exchange.prevent_clearing_proof_mutation();
        CREATE TRIGGER trg_clearing_proofs_append_only
          BEFORE UPDATE OR DELETE ON exchange.clearing_proofs
          FOR EACH ROW EXECUTE FUNCTION exchange.prevent_clearing_proof_mutation();
        CREATE TRIGGER trg_clearing_statements_append_only
          BEFORE UPDATE OR DELETE ON exchange.clearing_statements
          FOR EACH ROW EXECUTE FUNCTION exchange.prevent_clearing_proof_mutation();
        CREATE TRIGGER trg_clearing_exports_append_only
          BEFORE UPDATE OR DELETE ON exchange.clearing_accounting_exports
          FOR EACH ROW EXECUTE FUNCTION exchange.prevent_clearing_proof_mutation();
        """
    )
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA exchange TO coop_app;
            REVOKE UPDATE, DELETE ON exchange.clearing_input_snapshots,
              exchange.clearing_entries, exchange.clearing_positions,
              exchange.clearing_approvals, exchange.clearing_proofs,
              exchange.clearing_statements, exchange.clearing_accounting_exports FROM coop_app;
          END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM exchange.clearing_policies)
             OR EXISTS (SELECT 1 FROM exchange.clearing_cycles)
             OR EXISTS (SELECT 1 FROM exchange.clearing_entries)
             OR EXISTS (SELECT 1 FROM exchange.obligations WHERE quantity_cleared > 0)
             OR EXISTS (
               SELECT 1 FROM identity.role_assignments
               WHERE role_code IN ('CLEARING_OPERATOR','CLEARING_CONTROLLER','CLEARING_FINALIZER')
             ) THEN
            RAISE EXCEPTION 'cannot downgrade 0009: clearing records or roles would be lost';
          END IF;
        END
        $$;
        """
    )
    op.execute("DROP FUNCTION IF EXISTS exchange.prevent_clearing_proof_mutation CASCADE")
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR'
            )
          );
        """
    )
    op.execute("ALTER TABLE exchange.obligations DROP CONSTRAINT ck_obligations_quantities_bounded")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("obligations", "clearing_allowed", schema="exchange")
    op.drop_column("obligations", "quantity_cleared", schema="exchange")
    op.execute(
        """
        ALTER TABLE exchange.obligations
          ADD CONSTRAINT ck_obligations_quantities_bounded CHECK (
            quantity_submitted >= 0
            AND quantity_fulfilled >= 0
            AND quantity_submitted + quantity_fulfilled <= quantity_total
          )
        """
    )
    op.drop_index(
        "ix_clearing_disputes_cycle_status", table_name="clearing_disputes", schema="exchange"
    )
    op.drop_table("clearing_disputes", schema="exchange")
    op.drop_index(
        "ix_clearing_entries_cycle_member", table_name="clearing_entries", schema="exchange"
    )
    op.drop_index(
        "ix_clearing_entries_cycle_creditor", table_name="clearing_entries", schema="exchange"
    )
    op.drop_table("clearing_entries", schema="exchange")
    op.drop_table("clearing_statements", schema="exchange")
    op.drop_table("clearing_proofs", schema="exchange")
    op.drop_table("clearing_positions", schema="exchange")
    op.drop_table("clearing_input_snapshots", schema="exchange")
    op.drop_table("clearing_approvals", schema="exchange")
    op.drop_table("clearing_accounting_exports", schema="exchange")
    op.drop_index("ix_clearing_cycles_period", table_name="clearing_cycles", schema="exchange")
    op.drop_index(
        "ix_clearing_cycles_cooperative_status", table_name="clearing_cycles", schema="exchange"
    )
    op.drop_table("clearing_cycles", schema="exchange")
    op.drop_index(
        "uq_clearing_policy_active",
        table_name="clearing_policies",
        schema="exchange",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(
        "ix_clearing_policies_cooperative_status", table_name="clearing_policies", schema="exchange"
    )
    op.drop_table("clearing_policies", schema="exchange")
    # ### end Alembic commands ###
