"""trust disputes appeals reputation

Revision ID: 0010_trust_procedural_fairness
Revises: 0009_local_clearing
Create Date: 2026-07-21 08:08:27.305177
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010_trust_procedural_fairness"
down_revision: str | None = "0009_local_clearing"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS trust")
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR','ARBITRATOR'
            )
          );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trust_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("policy_code", sa.String(length=40), nullable=False),
        sa.Column("semantic_version", sa.String(length=24), nullable=False),
        sa.Column("appeal_window_seconds", sa.Integer(), nullable=False),
        sa.Column("max_protective_seconds", sa.Integer(), nullable=False),
        sa.Column("panel_quorum", sa.Integer(), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("approved_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'PROPOSED' AND approved_event_id IS NULL) OR (status IN ('ACTIVE','SUPERSEDED') AND approved_event_id IS NOT NULL) OR status = 'REJECTED'",
            name=op.f("ck_trust_policies_approval_consistent"),
        ),
        sa.CheckConstraint(
            "policy_code = 'TRUST_PROCEDURE'", name=op.f("ck_trust_policies_code_allowed")
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','ACTIVE','REJECTED','SUPERSEDED')",
            name=op.f("ck_trust_policies_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_trust_policies_terms_hash_sha256")
        ),
        sa.CheckConstraint(
            "appeal_window_seconds BETWEEN 0 AND 2592000",
            name=op.f("ck_trust_policies_appeal_window_bounded"),
        ),
        sa.CheckConstraint(
            "max_protective_seconds BETWEEN 1 AND 2592000",
            name=op.f("ck_trust_policies_protective_window_bounded"),
        ),
        sa.CheckConstraint(
            "panel_quorum BETWEEN 1 AND 9", name=op.f("ck_trust_policies_panel_quorum_bounded")
        ),
        sa.CheckConstraint(
            "policy_version >= 1 AND version >= 1", name=op.f("ck_trust_policies_versions_positive")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_trust_policies_approved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_trust_policies_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_trust_policies_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_trust_policies_approved_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_trust_policies_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_trust_policies_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_trust_policies_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_trust_policies_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_trust_policies_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trust_policies")),
        sa.UniqueConstraint("approved_event_id", name=op.f("uq_trust_policies_approved_event_id")),
        sa.UniqueConstraint("cooperative_id", "policy_version", name="uq_trust_policy_version"),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_trust_policies_proposed_event_id")),
        schema="trust",
    )
    op.create_index(
        "uq_trust_policy_active",
        "trust_policies",
        ["cooperative_id"],
        unique=True,
        schema="trust",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("case_reference", sa.String(length=80), nullable=False),
        sa.Column("subject_member_id", sa.UUID(), nullable=False),
        sa.Column("claimant_member_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_reference", sa.String(length=120), nullable=False),
        sa.Column("source_event_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.String(length=240), nullable=False),
        sa.Column("facts", sa.Text(), nullable=False),
        sa.Column("requested_outcome", sa.Text(), nullable=False),
        sa.Column("confidentiality", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column("opened_by_member_id", sa.UUID(), nullable=False),
        sa.Column("opened_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("opened_event_id", sa.UUID(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("response_evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("responded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("response_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_decision_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("appeal_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "confidentiality IN ('NORMAL','RESTRICTED')",
            name=op.f("ck_cases_confidentiality_allowed"),
        ),
        sa.CheckConstraint(
            "source_type IN ('LIABILITY','EXCHANGE','CLEARING','INVENTORY','RIGHTS','NODE','OTHER')",
            name=op.f("ck_cases_source_type_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','RESPONSE_RECEIVED','READY_FOR_DECISION','DECIDED','UNDER_APPEAL','REMANDED','CLOSED')",
            name=op.f("ck_cases_status_allowed"),
        ),
        sa.CheckConstraint(
            "(response_event_id IS NULL AND response_text IS NULL AND responded_at IS NULL) OR (response_event_id IS NOT NULL AND response_text IS NOT NULL AND responded_at IS NOT NULL)",
            name=op.f("ck_cases_response_consistent"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_cases_version_positive")),
        sa.ForeignKeyConstraint(
            ["claimant_member_id"],
            ["identity.members.id"],
            name=op.f("fk_cases_claimant_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_cases_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_cases_opened_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_cases_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_cases_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_cases_opened_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["trust.trust_policies.id"],
            name=op.f("fk_cases_policy_id_trust_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responded_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_cases_responded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["response_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_cases_response_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_member_id"],
            ["identity.members.id"],
            name=op.f("fk_cases_subject_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("cooperative_id", "case_reference", name="uq_trust_case_reference"),
        sa.UniqueConstraint("opened_event_id", name=op.f("uq_cases_opened_event_id")),
        sa.UniqueConstraint("response_event_id", name=op.f("uq_cases_response_event_id")),
        schema="trust",
    )
    op.create_index(
        "ix_trust_cases_cooperative_status",
        "cases",
        ["cooperative_id", "status"],
        unique=False,
        schema="trust",
    )
    op.create_index(
        "ix_trust_cases_subject_status",
        "cases",
        ["subject_member_id", "status"],
        unique=False,
        schema="trust",
    )
    op.create_table(
        "arbitration_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("decision_round", sa.Integer(), nullable=False),
        sa.Column("related_object_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("standard_of_proof", sa.String(length=120), nullable=False),
        sa.Column("fault_class", sa.String(length=32), nullable=True),
        sa.Column("causal_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("established_loss", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("consequence_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("panel_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("issued_by_user_id", sa.UUID(), nullable=False),
        sa.Column("issued_by_member_id", sa.UUID(), nullable=False),
        sa.Column("issued_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("issued_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "fault_class IS NULL OR fault_class IN ('FORCE_MAJEURE','GOOD_FAITH_ERROR','NEGLIGENCE','GROSS_NEGLIGENCE','INTENT','COLLUSION')",
            name=op.f("ck_arbitration_decisions_fault_allowed"),
        ),
        sa.CheckConstraint(
            "outcome IN ('SUBSTANTIATED','PARTLY_SUBSTANTIATED','UNSUBSTANTIATED','AFFIRMED','MODIFIED','OVERTURNED','REMANDED')",
            name=op.f("ck_arbitration_decisions_outcome_allowed"),
        ),
        sa.CheckConstraint(
            "stage IN ('ORIGINAL','APPEAL')", name=op.f("ck_arbitration_decisions_stage_allowed")
        ),
        sa.CheckConstraint(
            "decision_round >= 1", name=op.f("ck_arbitration_decisions_round_positive")
        ),
        sa.CheckConstraint(
            "established_loss IS NULL OR established_loss >= 0",
            name=op.f("ck_arbitration_decisions_loss_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["trust.cases.id"],
            name=op.f("fk_arbitration_decisions_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_arbitration_decisions_issued_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_arbitration_decisions_issued_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_arbitration_decisions_issued_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_arbitration_decisions_issued_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_arbitration_decisions")),
        sa.UniqueConstraint("case_id", "stage", "decision_round", name="uq_trust_decision_round"),
        sa.UniqueConstraint(
            "issued_event_id", name=op.f("uq_arbitration_decisions_issued_event_id")
        ),
        schema="trust",
    )
    op.create_index(
        "ix_trust_decisions_case_stage",
        "arbitration_decisions",
        ["case_id", "stage"],
        unique=False,
        schema="trust",
    )
    op.create_table(
        "conflict_declarations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("assessment", sa.String(length=16), nullable=False),
        sa.Column("relationship", sa.String(length=120), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "declared_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "assessment IN ('CLEAR','CONFLICT')",
            name=op.f("ck_conflict_declarations_assessment_allowed"),
        ),
        sa.CheckConstraint(
            "stage IN ('ORIGINAL','APPEAL','REHABILITATION')",
            name=op.f("ck_conflict_declarations_stage_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["trust.cases.id"],
            name=op.f("fk_conflict_declarations_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_conflict_declarations_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_conflict_declarations_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_conflict_declarations_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity.users.id"],
            name=op.f("fk_conflict_declarations_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conflict_declarations")),
        sa.UniqueConstraint(
            "case_id", "stage", "member_id", name="uq_trust_conflict_case_stage_member"
        ),
        sa.UniqueConstraint("event_id", name=op.f("uq_conflict_declarations_event_id")),
        schema="trust",
    )
    op.create_table(
        "protective_measures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("subject_member_id", sa.UUID(), nullable=False),
        sa.Column("measure_type", sa.String(length=32), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("imposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("imposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("imposed_event_id", sa.UUID(), nullable=False),
        sa.Column("lifted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("lifted_by_member_id", sa.UUID(), nullable=True),
        sa.Column("lifted_event_id", sa.UUID(), nullable=True),
        sa.Column("lift_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND lifted_event_id IS NULL) OR (status IN ('LIFTED','REVOKED') AND lifted_event_id IS NOT NULL) OR status = 'EXPIRED'",
            name=op.f("ck_protective_measures_lifecycle_consistent"),
        ),
        sa.CheckConstraint(
            "measure_type IN ('ADDITIONAL_REVIEW','LIMIT_SCOPE','SUSPEND_ROLE','SUSPEND_KEY','BLOCK_NEW_GUARANTEES')",
            name=op.f("ck_protective_measures_type_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','LIFTED','EXPIRED','REVOKED')",
            name=op.f("ck_protective_measures_status_allowed"),
        ),
        sa.CheckConstraint(
            "expires_at > starts_at", name=op.f("ck_protective_measures_period_ordered")
        ),
        sa.CheckConstraint(
            "review_at <= expires_at", name=op.f("ck_protective_measures_review_before_expiry")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_protective_measures_version_positive")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["trust.cases.id"],
            name=op.f("fk_protective_measures_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["imposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_protective_measures_imposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["imposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_protective_measures_imposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["imposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_protective_measures_imposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["imposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_protective_measures_imposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lifted_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_protective_measures_lifted_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lifted_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_protective_measures_lifted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lifted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_protective_measures_lifted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_member_id"],
            ["identity.members.id"],
            name=op.f("fk_protective_measures_subject_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protective_measures")),
        sa.UniqueConstraint(
            "imposed_event_id", name=op.f("uq_protective_measures_imposed_event_id")
        ),
        sa.UniqueConstraint("lifted_event_id", name=op.f("uq_protective_measures_lifted_event_id")),
        schema="trust",
    )
    op.create_index(
        "ix_trust_measures_subject_status",
        "protective_measures",
        ["subject_member_id", "status"],
        unique=False,
        schema="trust",
    )
    op.create_table(
        "rehabilitation_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("subject_member_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("completion_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_member_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("closed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("closed_by_member_id", sa.UUID(), nullable=True),
        sa.Column("closed_event_id", sa.UUID(), nullable=True),
        sa.Column("closure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND closed_event_id IS NULL) OR (status IN ('COMPLETED','CANCELLED') AND closed_event_id IS NOT NULL)",
            name=op.f("ck_rehabilitation_plans_closure_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','COMPLETED','CANCELLED')",
            name=op.f("ck_rehabilitation_plans_status_allowed"),
        ),
        sa.CheckConstraint(
            "due_at > starts_at", name=op.f("ck_rehabilitation_plans_period_ordered")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_rehabilitation_plans_version_positive")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["trust.cases.id"],
            name=op.f("fk_rehabilitation_plans_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rehabilitation_plans_closed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_rehabilitation_plans_closed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rehabilitation_plans_closed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rehabilitation_plans_created_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_rehabilitation_plans_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rehabilitation_plans_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["trust.arbitration_decisions.id"],
            name=op.f("fk_rehabilitation_plans_decision_id_arbitration_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rehabilitation_plans_subject_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rehabilitation_plans")),
        sa.UniqueConstraint(
            "closed_event_id", name=op.f("uq_rehabilitation_plans_closed_event_id")
        ),
        sa.UniqueConstraint(
            "created_event_id", name=op.f("uq_rehabilitation_plans_created_event_id")
        ),
        schema="trust",
    )
    op.create_index(
        "ix_rehabilitation_plans_subject_status",
        "rehabilitation_plans",
        ["subject_member_id", "status"],
        unique=False,
        schema="trust",
    )
    op.create_table(
        "reputation_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("subject_member_id", sa.UUID(), nullable=False),
        sa.Column("context", sa.String(length=32), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("observation_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_event_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("appeal_state", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("corrects_event_id", sa.UUID(), nullable=True),
        sa.Column("recorded_by_user_id", sa.UUID(), nullable=False),
        sa.Column("recorded_by_member_id", sa.UUID(), nullable=False),
        sa.Column("recorded_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(classification = 'CORRECTION' AND corrects_event_id IS NOT NULL) OR (classification <> 'CORRECTION' AND corrects_event_id IS NULL)",
            name=op.f("ck_reputation_events_correction_consistent"),
        ),
        sa.CheckConstraint(
            "appeal_state IN ('NONE','PENDING','AFFIRMED','OVERTURNED')",
            name=op.f("ck_reputation_events_appeal_state_allowed"),
        ),
        sa.CheckConstraint(
            "classification IN ('FULFILLED','BREACH','SELF_REPORTED_ERROR','CORRECTION','REHABILITATION')",
            name=op.f("ck_reputation_events_classification_allowed"),
        ),
        sa.CheckConstraint(
            "context IN ('SUPPLY','QUALITY','STORAGE','LOGISTICS','SERVICE','OBLIGATION','GUARANTEE','WAREHOUSE_CONTROL','AUDIT','ARBITRATION','FUND_GOVERNANCE','NODE_SECURITY')",
            name=op.f("ck_reputation_events_context_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','DISPUTED','VOIDED')",
            name=op.f("ck_reputation_events_status_allowed"),
        ),
        sa.CheckConstraint(
            "visibility IN ('PARTICIPANT','COOPERATIVE','RESTRICTED')",
            name=op.f("ck_reputation_events_visibility_allowed"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_reputation_events_confidence_bounded"),
        ),
        sa.CheckConstraint(
            "observation_end >= observation_start",
            name=op.f("ck_reputation_events_observation_ordered"),
        ),
        sa.CheckConstraint(
            "severity BETWEEN 0 AND 5", name=op.f("ck_reputation_events_severity_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["trust.cases.id"],
            name=op.f("fk_reputation_events_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_reputation_events_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["corrects_event_id"],
            ["trust.reputation_events.id"],
            name=op.f("fk_reputation_events_corrects_event_id_reputation_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["trust.arbitration_decisions.id"],
            name=op.f("fk_reputation_events_decision_id_arbitration_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_reputation_events_recorded_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_reputation_events_recorded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_reputation_events_recorded_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_member_id"],
            ["identity.members.id"],
            name=op.f("fk_reputation_events_subject_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reputation_events")),
        sa.UniqueConstraint(
            "recorded_event_id", name=op.f("uq_reputation_events_recorded_event_id")
        ),
        schema="trust",
    )
    op.create_index(
        "ix_reputation_events_subject_context",
        "reputation_events",
        ["subject_member_id", "context"],
        unique=False,
        schema="trust",
    )
    op.create_table(
        "sanctions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("subject_member_id", sa.UUID(), nullable=False),
        sa.Column("measure_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("appeal_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("finalized_by_user_id", sa.UUID(), nullable=True),
        sa.Column("finalized_by_member_id", sa.UUID(), nullable=True),
        sa.Column("finalized_event_id", sa.UUID(), nullable=True),
        sa.Column("revoked_event_id", sa.UUID(), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status IN ('PROPOSED','PENDING_APPEAL') AND finalized_event_id IS NULL) OR (status IN ('ACTIVE','COMPLETED','CORRECTED') AND finalized_event_id IS NOT NULL) OR status = 'REVOKED'",
            name=op.f("ck_sanctions_finalization_consistent"),
        ),
        sa.CheckConstraint(
            "measure_type IN ('WARNING','TRAINING','ADDITIONAL_REVIEW','LIMIT_SCOPE','SUSPEND_ROLE','BLOCK_NEW_GUARANTEES','TERMINATE_ROLE')",
            name=op.f("ck_sanctions_type_allowed"),
        ),
        sa.CheckConstraint(
            "severity IN ('LOW','MEDIUM','HIGH','CRITICAL')",
            name=op.f("ck_sanctions_severity_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','PENDING_APPEAL','ACTIVE','REVOKED','COMPLETED','CORRECTED')",
            name=op.f("ck_sanctions_status_allowed"),
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > starts_at", name=op.f("ck_sanctions_period_ordered")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_sanctions_version_positive")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["trust.cases.id"],
            name=op.f("fk_sanctions_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["trust.arbitration_decisions.id"],
            name=op.f("fk_sanctions_decision_id_arbitration_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finalized_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_sanctions_finalized_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finalized_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_sanctions_finalized_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finalized_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sanctions_finalized_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_sanctions_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_sanctions_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sanctions_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sanctions_revoked_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_member_id"],
            ["identity.members.id"],
            name=op.f("fk_sanctions_subject_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sanctions")),
        sa.UniqueConstraint("finalized_event_id", name=op.f("uq_sanctions_finalized_event_id")),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_sanctions_proposed_event_id")),
        schema="trust",
    )
    op.create_index(
        "ix_trust_sanctions_subject_status",
        "sanctions",
        ["subject_member_id", "status"],
        unique=False,
        schema="trust",
    )
    op.create_table(
        "appeals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("original_decision_id", sa.UUID(), nullable=False),
        sa.Column("sanction_id", sa.UUID(), nullable=True),
        sa.Column("appellant_member_id", sa.UUID(), nullable=False),
        sa.Column("grounds", sa.Text(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_event_id", sa.UUID(), nullable=False),
        sa.Column("appeal_decision_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=True),
        sa.Column("decided_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'SUBMITTED' AND appeal_decision_id IS NULL AND outcome IS NULL) OR (status = 'DECIDED' AND appeal_decision_id IS NOT NULL AND outcome IS NOT NULL) OR status = 'WITHDRAWN'",
            name=op.f("ck_appeals_decision_consistent"),
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('AFFIRMED','MODIFIED','OVERTURNED','REMANDED')",
            name=op.f("ck_appeals_outcome_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('SUBMITTED','DECIDED','WITHDRAWN')", name=op.f("ck_appeals_status_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["appeal_decision_id"],
            ["trust.arbitration_decisions.id"],
            name=op.f("fk_appeals_appeal_decision_id_arbitration_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["appellant_member_id"],
            ["identity.members.id"],
            name=op.f("fk_appeals_appellant_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["trust.cases.id"],
            name=op.f("fk_appeals_case_id_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_appeals_decided_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["original_decision_id"],
            ["trust.arbitration_decisions.id"],
            name=op.f("fk_appeals_original_decision_id_arbitration_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sanction_id"],
            ["trust.sanctions.id"],
            name=op.f("fk_appeals_sanction_id_sanctions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_appeals_submitted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_appeals_submitted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appeals")),
        sa.UniqueConstraint("original_decision_id", name="uq_trust_appeal_original_decision"),
        sa.UniqueConstraint("submitted_event_id", name=op.f("uq_appeals_submitted_event_id")),
        schema="trust",
    )
    op.create_index(
        "ix_trust_appeals_case_status",
        "appeals",
        ["case_id", "status"],
        unique=False,
        schema="trust",
    )
    op.create_table(
        "rehabilitation_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("completion_criterion", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("completed_by_member_id", sa.UUID(), nullable=True),
        sa.Column("completed_event_id", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'PENDING' AND completed_event_id IS NULL) OR (status IN ('COMPLETED','WAIVED') AND completed_event_id IS NOT NULL)",
            name=op.f("ck_rehabilitation_steps_completion_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','COMPLETED','WAIVED')",
            name=op.f("ck_rehabilitation_steps_status_allowed"),
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_rehabilitation_steps_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["completed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rehabilitation_steps_completed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_rehabilitation_steps_completed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rehabilitation_steps_completed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["trust.rehabilitation_plans.id"],
            name=op.f("fk_rehabilitation_steps_plan_id_rehabilitation_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rehabilitation_steps")),
        sa.UniqueConstraint(
            "completed_event_id", name=op.f("uq_rehabilitation_steps_completed_event_id")
        ),
        sa.UniqueConstraint("plan_id", "sequence", name="uq_rehabilitation_step_sequence"),
        schema="trust",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION trust.prevent_immutable_record_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'trust decision records are append-only';
        END;
        $$;
        CREATE TRIGGER trg_trust_decisions_append_only
          BEFORE UPDATE OR DELETE ON trust.arbitration_decisions
          FOR EACH ROW EXECUTE FUNCTION trust.prevent_immutable_record_mutation();
        CREATE TRIGGER trg_trust_conflicts_append_only
          BEFORE UPDATE OR DELETE ON trust.conflict_declarations
          FOR EACH ROW EXECUTE FUNCTION trust.prevent_immutable_record_mutation();
        CREATE TRIGGER trg_reputation_events_append_only
          BEFORE UPDATE OR DELETE ON trust.reputation_events
          FOR EACH ROW EXECUTE FUNCTION trust.prevent_immutable_record_mutation();
        """
    )
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT USAGE ON SCHEMA trust TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA trust TO coop_app;
            REVOKE DELETE ON ALL TABLES IN SCHEMA trust FROM coop_app;
            REVOKE UPDATE ON trust.arbitration_decisions,
              trust.conflict_declarations, trust.reputation_events FROM coop_app;
          END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM trust.trust_policies)
             OR EXISTS (SELECT 1 FROM trust.cases)
             OR EXISTS (SELECT 1 FROM trust.arbitration_decisions)
             OR EXISTS (SELECT 1 FROM trust.reputation_events)
             OR EXISTS (
               SELECT 1 FROM identity.role_assignments
               WHERE role_code = 'ARBITRATOR'
             ) THEN
            RAISE EXCEPTION 'cannot downgrade 0010: trust records or roles would be lost';
          END IF;
        END
        $$;
        """
    )
    op.execute("DROP FUNCTION IF EXISTS trust.prevent_immutable_record_mutation CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rehabilitation_steps", schema="trust")
    op.drop_index("ix_trust_appeals_case_status", table_name="appeals", schema="trust")
    op.drop_table("appeals", schema="trust")
    op.drop_index("ix_trust_sanctions_subject_status", table_name="sanctions", schema="trust")
    op.drop_table("sanctions", schema="trust")
    op.drop_index(
        "ix_reputation_events_subject_context", table_name="reputation_events", schema="trust"
    )
    op.drop_table("reputation_events", schema="trust")
    op.drop_index(
        "ix_rehabilitation_plans_subject_status", table_name="rehabilitation_plans", schema="trust"
    )
    op.drop_table("rehabilitation_plans", schema="trust")
    op.drop_index(
        "ix_trust_measures_subject_status", table_name="protective_measures", schema="trust"
    )
    op.drop_table("protective_measures", schema="trust")
    op.drop_table("conflict_declarations", schema="trust")
    op.drop_index(
        "ix_trust_decisions_case_stage", table_name="arbitration_decisions", schema="trust"
    )
    op.drop_table("arbitration_decisions", schema="trust")
    op.drop_index("ix_trust_cases_subject_status", table_name="cases", schema="trust")
    op.drop_index("ix_trust_cases_cooperative_status", table_name="cases", schema="trust")
    op.drop_table("cases", schema="trust")
    op.drop_index(
        "uq_trust_policy_active",
        table_name="trust_policies",
        schema="trust",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("trust_policies", schema="trust")
    # ### end Alembic commands ###
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR'
            )
          );
        """
    )
    op.execute("DROP SCHEMA trust")
