"""solidarity aid vertical flow

Revision ID: 0011_solidarity_aid
Revises: 0010_trust_procedural_fairness
Create Date: 2026-07-21 10:20:35.141809
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011_solidarity_aid"
down_revision: str | None = "0010_trust_procedural_fairness"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS solidarity")
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SOLIDARITY_OPERATOR','SOLIDARITY_CONTROLLER',
              'SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR','ARBITRATOR'
            )
          );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("fund_code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("residue_rule", sa.String(length=40), nullable=False),
        sa.Column("admin_expense_limit", sa.Numeric(precision=8, scale=7), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("approved_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'DRAFT' AND approved_event_id IS NULL) OR (status IN ('ACTIVE','SUSPENDED','CLOSED') AND approved_event_id IS NOT NULL)",
            name=op.f("ck_funds_approval_consistent"),
        ),
        sa.CheckConstraint(
            "residue_rule IN ('RETAIN_IN_FUND','RETURN_TO_DONORS','TRANSFER_APPROVED_CAMPAIGN')",
            name=op.f("ck_funds_residue_rule_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','SUSPENDED','CLOSED')",
            name=op.f("ck_funds_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_funds_terms_hash_sha256")
        ),
        sa.CheckConstraint(
            "admin_expense_limit >= 0 AND admin_expense_limit <= 1",
            name=op.f("ck_funds_admin_expense_limit_bounded"),
        ),
        sa.CheckConstraint(
            "version >= 1 AND policy_version >= 1", name=op.f("ck_funds_versions_positive")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_funds_approved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_funds_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_funds_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_funds_approved_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_funds_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_funds_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_funds_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_funds_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_funds_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funds")),
        sa.UniqueConstraint("approved_event_id", name=op.f("uq_funds_approved_event_id")),
        sa.UniqueConstraint("cooperative_id", "fund_code", name="uq_solidarity_fund_code"),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_funds_proposed_event_id")),
        schema="solidarity",
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.UUID(), nullable=False),
        sa.Column("campaign_code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("public_purpose", sa.Text(), nullable=False),
        sa.Column("eligibility_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("accepted_forms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("residue_rule", sa.String(length=40), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_member_id", sa.UUID(), nullable=False),
        sa.Column("created_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=True),
        sa.Column("opened_by_member_id", sa.UUID(), nullable=True),
        sa.Column("opened_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("opened_event_id", sa.UUID(), nullable=True),
        sa.Column("closed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("closed_by_member_id", sa.UUID(), nullable=True),
        sa.Column("closed_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("closed_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'DRAFT' AND opened_event_id IS NULL) OR (status IN ('OPEN','SUSPENDED') AND opened_event_id IS NOT NULL AND closed_event_id IS NULL) OR (status IN ('CLOSED','CANCELLED') AND closed_event_id IS NOT NULL)",
            name=op.f("ck_campaigns_lifecycle_consistent"),
        ),
        sa.CheckConstraint(
            "residue_rule IN ('RETAIN_IN_FUND','RETURN_TO_DONORS','TRANSFER_APPROVED_CAMPAIGN')",
            name=op.f("ck_campaigns_residue_rule_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','OPEN','SUSPENDED','CLOSED','CANCELLED')",
            name=op.f("ck_campaigns_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_campaigns_terms_hash_sha256")
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_campaigns_period_ordered")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_campaigns_version_positive")),
        sa.ForeignKeyConstraint(
            ["closed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_campaigns_closed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_campaigns_closed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_campaigns_closed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_campaigns_closed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_campaigns_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_campaigns_created_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_campaigns_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_campaigns_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_campaigns_created_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fund_id"],
            ["solidarity.funds.id"],
            name=op.f("fk_campaigns_fund_id_funds"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_campaigns_opened_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_campaigns_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_campaigns_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_campaigns_opened_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("closed_event_id", name=op.f("uq_campaigns_closed_event_id")),
        sa.UniqueConstraint("cooperative_id", "campaign_code", name="uq_solidarity_campaign_code"),
        sa.UniqueConstraint("created_event_id", name=op.f("uq_campaigns_created_event_id")),
        sa.UniqueConstraint("opened_event_id", name=op.f("uq_campaigns_opened_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_solidarity_campaigns_status",
        "campaigns",
        ["cooperative_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("recipient_member_id", sa.UUID(), nullable=False),
        sa.Column("need_category", sa.String(length=24), nullable=False),
        sa.Column("requested_form", sa.String(length=24), nullable=False),
        sa.Column("requested_unit_code", sa.String(length=24), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("privacy_scope", sa.String(length=24), nullable=False),
        sa.Column("private_evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by_member_id", sa.UUID(), nullable=False),
        sa.Column("submitted_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("submitted_event_id", sa.UUID(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_member_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_event_id", sa.UUID(), nullable=True),
        sa.Column("eligibility_note", sa.Text(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "need_category IN ('BASIC_FOOD','MEDICAL','SHELTER','TRANSPORT','CARE','OTHER')",
            name=op.f("ck_applications_need_category_allowed"),
        ),
        sa.CheckConstraint(
            "privacy_scope IN ('PARTICIPANT_STAFF','RESTRICTED')",
            name=op.f("ck_applications_privacy_allowed"),
        ),
        sa.CheckConstraint(
            "requested_form IN ('MONEY','GOODS','LABOR','SERVICE','LOGISTICS','INFRASTRUCTURE')",
            name=op.f("ck_applications_form_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('SUBMITTED','ELIGIBLE','REJECTED','ALLOCATED','CLOSED')",
            name=op.f("ck_applications_status_allowed"),
        ),
        sa.CheckConstraint(
            "requested_quantity > 0", name=op.f("ck_applications_quantity_positive")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_applications_version_positive")),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["solidarity.campaigns.id"],
            name=op.f("fk_applications_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_member_id"],
            ["identity.members.id"],
            name=op.f("fk_applications_recipient_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_applications_reviewed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_applications_reviewed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_applications_reviewed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_applications_reviewed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_applications_submitted_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_applications_submitted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_applications_submitted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_applications_submitted_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("reviewed_event_id", name=op.f("uq_applications_reviewed_event_id")),
        sa.UniqueConstraint("submitted_event_id", name=op.f("uq_applications_submitted_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_solidarity_applications_campaign_status",
        "applications",
        ["campaign_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_index(
        "ix_solidarity_applications_recipient",
        "applications",
        ["recipient_member_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "campaign_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("bucket_totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contribution_count", sa.Integer(), nullable=False),
        sa.Column("allocation_count", sa.Integer(), nullable=False),
        sa.Column("delivery_count", sa.Integer(), nullable=False),
        sa.Column("complaint_count", sa.Integer(), nullable=False),
        sa.Column("residue_rule", sa.String(length=40), nullable=False),
        sa.Column(
            "responsibility_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("report_hash", sa.String(length=71), nullable=False),
        sa.Column("generated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("generated_by_member_id", sa.UUID(), nullable=False),
        sa.Column("generated_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("generated_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "report_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_campaign_reports_hash_sha256")
        ),
        sa.CheckConstraint(
            "residue_rule IN ('RETAIN_IN_FUND','RETURN_TO_DONORS','TRANSFER_APPROVED_CAMPAIGN')",
            name=op.f("ck_campaign_reports_residue_rule_allowed"),
        ),
        sa.CheckConstraint(
            "contribution_count >= 0 AND allocation_count >= 0 AND delivery_count >= 0 AND complaint_count >= 0",
            name=op.f("ck_campaign_reports_counts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["solidarity.campaigns.id"],
            name=op.f("fk_campaign_reports_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_campaign_reports_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_campaign_reports_generated_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_campaign_reports_generated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generated_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_campaign_reports_generated_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generated_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_campaign_reports_generated_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_reports")),
        sa.UniqueConstraint("campaign_id", name="uq_solidarity_campaign_report"),
        sa.UniqueConstraint(
            "generated_event_id", name=op.f("uq_campaign_reports_generated_event_id")
        ),
        schema="solidarity",
    )
    op.create_table(
        "pledges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("donor_member_id", sa.UUID(), nullable=False),
        sa.Column("contribution_form", sa.String(length=24), nullable=False),
        sa.Column("unit_code", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_member_id", sa.UUID(), nullable=False),
        sa.Column("created_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("fulfilled_contribution_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'FULFILLED' AND fulfilled_contribution_id IS NOT NULL) OR (status <> 'FULFILLED' AND fulfilled_contribution_id IS NULL)",
            name=op.f("ck_pledges_fulfillment_consistent"),
        ),
        sa.CheckConstraint(
            "contribution_form IN ('MONEY','GOODS','LABOR','SERVICE','LOGISTICS','INFRASTRUCTURE')",
            name=op.f("ck_pledges_form_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','FULFILLED','CANCELLED','EXPIRED')",
            name=op.f("ck_pledges_status_allowed"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_pledges_quantity_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_pledges_version_positive")),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["solidarity.campaigns.id"],
            name=op.f("fk_pledges_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_pledges_cancelled_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_pledges_created_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_pledges_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_pledges_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_pledges_created_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["donor_member_id"],
            ["identity.members.id"],
            name=op.f("fk_pledges_donor_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pledges")),
        sa.UniqueConstraint("cancelled_event_id", name=op.f("uq_pledges_cancelled_event_id")),
        sa.UniqueConstraint("created_event_id", name=op.f("uq_pledges_created_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_solidarity_pledges_campaign_status",
        "pledges",
        ["campaign_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("recipient_member_id", sa.UUID(), nullable=False),
        sa.Column("contribution_form", sa.String(length=24), nullable=False),
        sa.Column("unit_code", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("public_summary", sa.String(length=240), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("policy_terms_hash", sa.String(length=71), nullable=False),
        sa.Column("allocation_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "allocation_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_allocations_hash_sha256")
        ),
        sa.CheckConstraint(
            "contribution_form IN ('MONEY','GOODS','LABOR','SERVICE','LOGISTICS','INFRASTRUCTURE')",
            name=op.f("ck_allocations_form_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','APPROVED','SUSPENDED','DELIVERED','CANCELLED')",
            name=op.f("ck_allocations_status_allowed"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_allocations_quantity_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_allocations_version_positive")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["solidarity.applications.id"],
            name=op.f("fk_allocations_application_id_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["solidarity.campaigns.id"],
            name=op.f("fk_allocations_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_allocations_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_allocations_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_allocations_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_allocations_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_member_id"],
            ["identity.members.id"],
            name=op.f("fk_allocations_recipient_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_allocations_proposed_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_solidarity_allocations_campaign_status",
        "allocations",
        ["campaign_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_index(
        "uq_solidarity_allocation_active_application",
        "allocations",
        ["application_id"],
        unique=True,
        schema="solidarity",
        postgresql_where=sa.text("status IN ('PROPOSED','APPROVED','SUSPENDED','DELIVERED')"),
    )
    op.create_table(
        "contributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("pledge_id", sa.UUID(), nullable=True),
        sa.Column("donor_member_id", sa.UUID(), nullable=False),
        sa.Column("contribution_form", sa.String(length=24), nullable=False),
        sa.Column("unit_code", sa.String(length=24), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("received_by_user_id", sa.UUID(), nullable=False),
        sa.Column("received_by_member_id", sa.UUID(), nullable=False),
        sa.Column("received_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("received_event_id", sa.UUID(), nullable=False),
        sa.Column("verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("verified_by_member_id", sa.UUID(), nullable=True),
        sa.Column("verified_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("verified_event_id", sa.UUID(), nullable=True),
        sa.Column("verification_note", sa.Text(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'RECEIVED' AND verified_event_id IS NULL) OR (status IN ('VERIFIED','REJECTED','REFUNDED') AND verified_event_id IS NOT NULL)",
            name=op.f("ck_contributions_verification_consistent"),
        ),
        sa.CheckConstraint(
            "contribution_form IN ('MONEY','GOODS','LABOR','SERVICE','LOGISTICS','INFRASTRUCTURE')",
            name=op.f("ck_contributions_form_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('RECEIVED','VERIFIED','REJECTED','REFUNDED')",
            name=op.f("ck_contributions_status_allowed"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_contributions_quantity_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_contributions_version_positive")),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["solidarity.campaigns.id"],
            name=op.f("fk_contributions_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["donor_member_id"],
            ["identity.members.id"],
            name=op.f("fk_contributions_donor_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pledge_id"],
            ["solidarity.pledges.id"],
            name=op.f("fk_contributions_pledge_id_pledges"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_contributions_received_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_contributions_received_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_contributions_received_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_contributions_received_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_contributions_verified_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_contributions_verified_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_contributions_verified_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_contributions_verified_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contributions")),
        sa.UniqueConstraint("pledge_id", name="uq_solidarity_contribution_pledge"),
        sa.UniqueConstraint("received_event_id", name=op.f("uq_contributions_received_event_id")),
        sa.UniqueConstraint("verified_event_id", name=op.f("uq_contributions_verified_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_solidarity_contributions_campaign_status",
        "contributions",
        ["campaign_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_foreign_key(
        "fk_pledges_fulfilled_contribution_id_contributions",
        "pledges",
        "contributions",
        ["fulfilled_contribution_id"],
        ["id"],
        source_schema="solidarity",
        referent_schema="solidarity",
        ondelete="RESTRICT",
    )
    op.create_table(
        "allocation_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("allocation_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("allocation_hash", sa.String(length=71), nullable=False),
        sa.Column("conflict_statement", sa.Text(), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=False),
        sa.Column("decided_by_member_id", sa.UUID(), nullable=False),
        sa.Column("decided_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("decided_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allocation_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_allocation_approvals_hash_sha256"),
        ),
        sa.CheckConstraint(
            "decision IN ('APPROVED','REJECTED')",
            name=op.f("ck_allocation_approvals_decision_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["solidarity.allocations.id"],
            name=op.f("fk_allocation_approvals_allocation_id_allocations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_allocation_approvals_decided_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_allocation_approvals_decided_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_allocation_approvals_decided_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_allocation_approvals_decided_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_approvals")),
        sa.UniqueConstraint("allocation_id", name="uq_solidarity_allocation_approval"),
        sa.UniqueConstraint(
            "decided_event_id", name=op.f("uq_allocation_approvals_decided_event_id")
        ),
        schema="solidarity",
    )
    op.create_table(
        "complaints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("allocation_id", sa.UUID(), nullable=True),
        sa.Column("contribution_id", sa.UUID(), nullable=True),
        sa.Column("complainant_member_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("summary", sa.String(length=240), nullable=False),
        sa.Column("privacy_scope", sa.String(length=24), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column("opened_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("opened_event_id", sa.UUID(), nullable=False),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("resolved_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("resolved_event_id", sa.UUID(), nullable=True),
        sa.Column("resolution_action", sa.String(length=32), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "category IN ('ELIGIBILITY','ALLOCATION','DELIVERY','CONTRIBUTION','PRIVACY','OTHER')",
            name=op.f("ck_complaints_category_allowed"),
        ),
        sa.CheckConstraint(
            "privacy_scope IN ('PARTICIPANT_STAFF','RESTRICTED')",
            name=op.f("ck_complaints_privacy_allowed"),
        ),
        sa.CheckConstraint(
            "resolution_action IS NULL OR resolution_action IN ('RESTORE_ALLOCATION','CANCEL_ALLOCATION','NOTE_ONLY')",
            name=op.f("ck_complaints_resolution_action_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','RESOLVED','REJECTED')", name=op.f("ck_complaints_status_allowed")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_complaints_version_positive")),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["solidarity.allocations.id"],
            name=op.f("fk_complaints_allocation_id_allocations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["solidarity.campaigns.id"],
            name=op.f("fk_complaints_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["complainant_member_id"],
            ["identity.members.id"],
            name=op.f("fk_complaints_complainant_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["contribution_id"],
            ["solidarity.contributions.id"],
            name=op.f("fk_complaints_contribution_id_contributions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_complaints_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_complaints_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_complaints_opened_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_complaints_resolved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_complaints_resolved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_complaints_resolved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_complaints_resolved_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaints")),
        sa.UniqueConstraint("opened_event_id", name=op.f("uq_complaints_opened_event_id")),
        sa.UniqueConstraint("resolved_event_id", name=op.f("uq_complaints_resolved_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_solidarity_complaints_campaign_status",
        "complaints",
        ["campaign_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("allocation_id", sa.UUID(), nullable=False),
        sa.Column("recipient_member_id", sa.UUID(), nullable=False),
        sa.Column("attestor_kind", sa.String(length=20), nullable=False),
        sa.Column("attested_by_user_id", sa.UUID(), nullable=False),
        sa.Column("attested_by_member_id", sa.UUID(), nullable=False),
        sa.Column("attested_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acknowledgement", sa.Text(), nullable=False),
        sa.Column("delivered_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attestor_kind IN ('RECIPIENT','REPRESENTATIVE','WITNESS')",
            name=op.f("ck_deliveries_attestor_kind_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["solidarity.allocations.id"],
            name=op.f("fk_deliveries_allocation_id_allocations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["attested_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_deliveries_attested_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["attested_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_deliveries_attested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["attested_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_deliveries_attested_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delivered_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_deliveries_delivered_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_member_id"],
            ["identity.members.id"],
            name=op.f("fk_deliveries_recipient_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("allocation_id", name="uq_solidarity_delivery_allocation"),
        sa.UniqueConstraint("delivered_event_id", name=op.f("uq_deliveries_delivered_event_id")),
        schema="solidarity",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION solidarity.prevent_immutable_record_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'solidarity approval, delivery, and report records are append-only';
        END;
        $$;
        CREATE TRIGGER trg_solidarity_approvals_append_only
          BEFORE UPDATE OR DELETE ON solidarity.allocation_approvals
          FOR EACH ROW EXECUTE FUNCTION solidarity.prevent_immutable_record_mutation();
        CREATE TRIGGER trg_solidarity_deliveries_append_only
          BEFORE UPDATE OR DELETE ON solidarity.deliveries
          FOR EACH ROW EXECUTE FUNCTION solidarity.prevent_immutable_record_mutation();
        CREATE TRIGGER trg_solidarity_reports_append_only
          BEFORE UPDATE OR DELETE ON solidarity.campaign_reports
          FOR EACH ROW EXECUTE FUNCTION solidarity.prevent_immutable_record_mutation();
        """
    )
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT USAGE ON SCHEMA solidarity TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA solidarity TO coop_app;
            REVOKE DELETE ON ALL TABLES IN SCHEMA solidarity FROM coop_app;
            REVOKE UPDATE ON solidarity.allocation_approvals,
              solidarity.deliveries, solidarity.campaign_reports FROM coop_app;
          END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM solidarity.funds)
             OR EXISTS (SELECT 1 FROM solidarity.campaigns)
             OR EXISTS (SELECT 1 FROM solidarity.contributions)
             OR EXISTS (SELECT 1 FROM solidarity.allocations)
             OR EXISTS (SELECT 1 FROM solidarity.deliveries)
             OR EXISTS (SELECT 1 FROM solidarity.campaign_reports)
             OR EXISTS (
               SELECT 1 FROM identity.role_assignments
               WHERE role_code IN ('SOLIDARITY_OPERATOR','SOLIDARITY_CONTROLLER')
             ) THEN
            RAISE EXCEPTION 'cannot downgrade 0011: solidarity records or roles would be lost';
          END IF;
        END
        $$;
        """
    )
    op.execute("DROP FUNCTION IF EXISTS solidarity.prevent_immutable_record_mutation CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deliveries", schema="solidarity")
    op.drop_index(
        "ix_solidarity_complaints_campaign_status", table_name="complaints", schema="solidarity"
    )
    op.drop_table("complaints", schema="solidarity")
    op.drop_table("allocation_approvals", schema="solidarity")
    op.drop_index(
        "ix_solidarity_contributions_campaign_status",
        table_name="contributions",
        schema="solidarity",
    )
    op.drop_constraint(
        "fk_pledges_fulfilled_contribution_id_contributions",
        "pledges",
        schema="solidarity",
        type_="foreignkey",
    )
    op.drop_table("contributions", schema="solidarity")
    op.drop_index(
        "uq_solidarity_allocation_active_application",
        table_name="allocations",
        schema="solidarity",
        postgresql_where=sa.text("status IN ('PROPOSED','APPROVED','SUSPENDED','DELIVERED')"),
    )
    op.drop_index(
        "ix_solidarity_allocations_campaign_status", table_name="allocations", schema="solidarity"
    )
    op.drop_table("allocations", schema="solidarity")
    op.drop_index(
        "ix_solidarity_pledges_campaign_status", table_name="pledges", schema="solidarity"
    )
    op.drop_table("pledges", schema="solidarity")
    op.drop_table("campaign_reports", schema="solidarity")
    op.drop_index(
        "ix_solidarity_applications_recipient", table_name="applications", schema="solidarity"
    )
    op.drop_index(
        "ix_solidarity_applications_campaign_status", table_name="applications", schema="solidarity"
    )
    op.drop_table("applications", schema="solidarity")
    op.drop_index("ix_solidarity_campaigns_status", table_name="campaigns", schema="solidarity")
    op.drop_table("campaigns", schema="solidarity")
    op.drop_table("funds", schema="solidarity")
    # ### end Alembic commands ###
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR','ARBITRATOR'
            )
          );
        """
    )
    op.execute("DROP SCHEMA solidarity")
