"""crisis reserves rationing

Revision ID: 0012_crisis_reserves
Revises: 0011_solidarity_aid
Create Date: 2026-07-21 13:21:02.001165
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0012_crisis_reserves"
down_revision: str | None = "0011_solidarity_aid"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SOLIDARITY_OPERATOR','SOLIDARITY_CONTROLLER',
              'CRISIS_OPERATOR','CRISIS_CONTROLLER',
              'SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR','ARBITRATOR'
            )
          );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crisis_mandates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("mandate_code", sa.String(length=64), nullable=False),
        sa.Column("crisis_type", sa.String(length=40), nullable=False),
        sa.Column("scope_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("exit_criteria", sa.Text(), nullable=False),
        sa.Column("safe_state", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("maximum_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("activated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("activated_by_member_id", sa.UUID(), nullable=True),
        sa.Column("activated_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("activated_event_id", sa.UUID(), nullable=True),
        sa.Column("closed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("closed_by_member_id", sa.UUID(), nullable=True),
        sa.Column("closed_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'DRAFT' AND activated_event_id IS NULL AND closed_event_id IS NULL) OR (status = 'ACTIVE' AND activated_event_id IS NOT NULL AND closed_event_id IS NULL) OR (status IN ('CLOSED','EXPIRED') AND activated_event_id IS NOT NULL AND closed_event_id IS NOT NULL)",
            name=op.f("ck_crisis_mandates_lifecycle_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','CLOSED','EXPIRED')",
            name=op.f("ck_crisis_mandates_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_crisis_mandates_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "jsonb_array_length(capabilities) > 0",
            name=op.f("ck_crisis_mandates_capability_required"),
        ),
        sa.CheckConstraint(
            "jsonb_array_length(evidence_ids) > 0",
            name=op.f("ck_crisis_mandates_evidence_required"),
        ),
        sa.CheckConstraint(
            "starts_at < review_at AND review_at <= expires_at AND expires_at <= maximum_end_at",
            name=op.f("ck_crisis_mandates_period_ordered"),
        ),
        sa.CheckConstraint(
            "version >= 1 AND policy_version >= 1",
            name=op.f("ck_crisis_mandates_versions_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["activated_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_crisis_mandates_activated_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["activated_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_crisis_mandates_activated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["activated_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_crisis_mandates_activated_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["activated_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_crisis_mandates_activated_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_crisis_mandates_closed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_crisis_mandates_closed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_crisis_mandates_closed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_crisis_mandates_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_crisis_mandates_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_crisis_mandates_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_crisis_mandates_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_crisis_mandates_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crisis_mandates")),
        sa.UniqueConstraint(
            "activated_event_id", name=op.f("uq_crisis_mandates_activated_event_id")
        ),
        sa.UniqueConstraint("closed_event_id", name=op.f("uq_crisis_mandates_closed_event_id")),
        sa.UniqueConstraint("cooperative_id", "mandate_code", name="uq_crisis_mandate_code"),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_crisis_mandates_proposed_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_crisis_mandates_status",
        "crisis_mandates",
        ["cooperative_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "reserve_targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("resource_code", sa.String(length=64), nullable=False),
        sa.Column("resource_name", sa.String(length=200), nullable=False),
        sa.Column("unit_code", sa.String(length=24), nullable=False),
        sa.Column("target_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("critical_minimum", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("warning_coverage_days", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("critical_coverage_days", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("max_snapshot_age_hours", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("approved_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'DRAFT' AND approved_event_id IS NULL) OR (status IN ('ACTIVE','RETIRED') AND approved_event_id IS NOT NULL)",
            name=op.f("ck_reserve_targets_approval_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','RETIRED')", name=op.f("ck_reserve_targets_status_allowed")
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_reserve_targets_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "critical_minimum >= 0 AND critical_minimum <= target_quantity",
            name=op.f("ck_reserve_targets_critical_minimum_bounded"),
        ),
        sa.CheckConstraint(
            "max_snapshot_age_hours BETWEEN 1 AND 720",
            name=op.f("ck_reserve_targets_snapshot_age_bounded"),
        ),
        sa.CheckConstraint("target_quantity > 0", name=op.f("ck_reserve_targets_target_positive")),
        sa.CheckConstraint(
            "version >= 1 AND policy_version >= 1",
            name=op.f("ck_reserve_targets_versions_positive"),
        ),
        sa.CheckConstraint(
            "warning_coverage_days >= critical_coverage_days AND critical_coverage_days >= 0",
            name=op.f("ck_reserve_targets_coverage_thresholds_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_reserve_targets_approved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_reserve_targets_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_reserve_targets_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_reserve_targets_approved_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_reserve_targets_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_reserve_targets_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_reserve_targets_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_reserve_targets_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_reserve_targets_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reserve_targets")),
        sa.UniqueConstraint("approved_event_id", name=op.f("uq_reserve_targets_approved_event_id")),
        sa.UniqueConstraint(
            "cooperative_id", "resource_code", "policy_version", name="uq_reserve_target_policy"
        ),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_reserve_targets_proposed_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_reserve_targets_active",
        "reserve_targets",
        ["cooperative_id", "resource_code", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "crisis_paper_forms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cooperative_id", sa.UUID(), nullable=False),
        sa.Column("mandate_id", sa.UUID(), nullable=False),
        sa.Column("serial_number", sa.String(length=64), nullable=False),
        sa.Column("checksum", sa.String(length=8), nullable=False),
        sa.Column("form_type", sa.String(length=32), nullable=False),
        sa.Column("assigned_to_member_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload_hash", sa.String(length=71), nullable=True),
        sa.Column("issued_by_user_id", sa.UUID(), nullable=False),
        sa.Column("issued_by_member_id", sa.UUID(), nullable=False),
        sa.Column("issued_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("issued_event_id", sa.UUID(), nullable=False),
        sa.Column("recorded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("recorded_by_member_id", sa.UUID(), nullable=True),
        sa.Column("recorded_event_id", sa.UUID(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "checksum ~ '^[0-9A-F]{8}$'", name=op.f("ck_crisis_paper_forms_checksum_format")
        ),
        sa.CheckConstraint(
            "form_type IN ('RESERVE_SNAPSHOT','RATION_ISSUANCE','INCIDENT','EXCEPTION')",
            name=op.f("ck_crisis_paper_forms_type_allowed"),
        ),
        sa.CheckConstraint(
            "payload_hash IS NULL OR payload_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_crisis_paper_forms_payload_hash_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('ISSUED','RECORDED','VOID','EXPIRED')",
            name=op.f("ck_crisis_paper_forms_status_allowed"),
        ),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_crisis_paper_forms_expiry_after_issue")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_member_id"],
            ["identity.members.id"],
            name=op.f("fk_crisis_paper_forms_assigned_to_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cooperative_id"],
            ["identity.cooperatives.id"],
            name=op.f("fk_crisis_paper_forms_cooperative_id_cooperatives"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_crisis_paper_forms_issued_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_crisis_paper_forms_issued_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_crisis_paper_forms_issued_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_crisis_paper_forms_issued_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["solidarity.crisis_mandates.id"],
            name=op.f("fk_crisis_paper_forms_mandate_id_crisis_mandates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_crisis_paper_forms_recorded_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_crisis_paper_forms_recorded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_crisis_paper_forms_recorded_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crisis_paper_forms")),
        sa.UniqueConstraint("cooperative_id", "serial_number", name="uq_crisis_paper_form_serial"),
        sa.UniqueConstraint("issued_event_id", name=op.f("uq_crisis_paper_forms_issued_event_id")),
        sa.UniqueConstraint(
            "recorded_event_id", name=op.f("uq_crisis_paper_forms_recorded_event_id")
        ),
        schema="solidarity",
    )
    op.create_table(
        "crisis_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mandate_id", sa.UUID(), nullable=False),
        sa.Column("report_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report_hash", sa.String(length=71), nullable=False),
        sa.Column("generated_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "report_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_crisis_reports_report_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["generated_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_crisis_reports_generated_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["solidarity.crisis_mandates.id"],
            name=op.f("fk_crisis_reports_mandate_id_crisis_mandates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crisis_reports")),
        sa.UniqueConstraint(
            "generated_event_id", name=op.f("uq_crisis_reports_generated_event_id")
        ),
        sa.UniqueConstraint("mandate_id", name="uq_crisis_report_mandate"),
        schema="solidarity",
    )
    op.create_table(
        "crisis_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mandate_id", sa.UUID(), nullable=False),
        sa.Column("decision_round", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("facts_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("previous_review_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("new_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_member_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('CONTINUE','EXTEND','CLOSE','EXPIRE')",
            name=op.f("ck_crisis_reviews_decision_allowed"),
        ),
        sa.CheckConstraint(
            "new_review_at IS NULL OR new_review_at < new_expires_at",
            name=op.f("ck_crisis_reviews_new_period_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_crisis_reviews_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["solidarity.crisis_mandates.id"],
            name=op.f("fk_crisis_reviews_mandate_id_crisis_mandates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_member_id"],
            ["identity.members.id"],
            name=op.f("fk_crisis_reviews_reviewer_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_crisis_reviews_reviewer_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["identity.users.id"],
            name=op.f("fk_crisis_reviews_reviewer_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crisis_reviews")),
        sa.UniqueConstraint("event_id", name=op.f("uq_crisis_reviews_event_id")),
        sa.UniqueConstraint("mandate_id", "decision_round", name="uq_crisis_review_round"),
        schema="solidarity",
    )
    op.create_table(
        "rationing_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mandate_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("formula", sa.String(length=32), nullable=False),
        sa.Column("eligibility_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("protected_minimum", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("maximum_per_member", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("period_hours", sa.Integer(), nullable=False),
        sa.Column("terms_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_member_id", sa.UUID(), nullable=True),
        sa.Column("approved_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "formula IN ('EQUAL_PER_MEMBER','WEIGHTED_PRIORITY')",
            name=op.f("ck_rationing_rules_formula_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','RETIRED')", name=op.f("ck_rationing_rules_status_allowed")
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_rationing_rules_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "period_hours BETWEEN 1 AND 720", name=op.f("ck_rationing_rules_period_bounded")
        ),
        sa.CheckConstraint(
            "protected_minimum >= 0 AND maximum_per_member > 0 AND protected_minimum <= maximum_per_member",
            name=op.f("ck_rationing_rules_limits_ordered"),
        ),
        sa.CheckConstraint(
            "version >= 1 AND policy_version >= 1",
            name=op.f("ck_rationing_rules_versions_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rationing_rules_approved_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_rationing_rules_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rationing_rules_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_rationing_rules_approved_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mandate_id"],
            ["solidarity.crisis_mandates.id"],
            name=op.f("fk_rationing_rules_mandate_id_crisis_mandates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rationing_rules_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_rationing_rules_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rationing_rules_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_rationing_rules_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["solidarity.reserve_targets.id"],
            name=op.f("fk_rationing_rules_target_id_reserve_targets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rationing_rules")),
        sa.UniqueConstraint("approved_event_id", name=op.f("uq_rationing_rules_approved_event_id")),
        sa.UniqueConstraint(
            "mandate_id", "target_id", "policy_version", name="uq_rationing_rule_policy"
        ),
        sa.UniqueConstraint("proposed_event_id", name=op.f("uq_rationing_rules_proposed_event_id")),
        schema="solidarity",
    )
    op.create_table(
        "reserve_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("physical_verified_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("committed_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("available_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("consumption_rate_per_day", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("coverage_days", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("expiring_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("quality_status", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=8, scale=7), nullable=False),
        sa.Column("reserve_level", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=71), nullable=False),
        sa.Column("recorded_by_user_id", sa.UUID(), nullable=False),
        sa.Column("recorded_by_member_id", sa.UUID(), nullable=False),
        sa.Column("recorded_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("recorded_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_status IN ('ACCEPTED','DEGRADED','REJECTED')",
            name=op.f("ck_reserve_snapshots_quality_allowed"),
        ),
        sa.CheckConstraint(
            "reserve_level IN ('UNKNOWN','NORMAL','WARNING','CRITICAL')",
            name=op.f("ck_reserve_snapshots_level_allowed"),
        ),
        sa.CheckConstraint(
            "snapshot_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_reserve_snapshots_snapshot_hash_sha256"),
        ),
        sa.CheckConstraint(
            "available_quantity = physical_verified_quantity - committed_quantity AND available_quantity >= 0",
            name=op.f("ck_reserve_snapshots_available_consistent"),
        ),
        sa.CheckConstraint(
            "committed_quantity >= 0", name=op.f("ck_reserve_snapshots_committed_nonnegative")
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_reserve_snapshots_confidence_bounded"),
        ),
        sa.CheckConstraint(
            "consumption_rate_per_day >= 0",
            name=op.f("ck_reserve_snapshots_consumption_nonnegative"),
        ),
        sa.CheckConstraint(
            "coverage_days IS NULL OR coverage_days >= 0",
            name=op.f("ck_reserve_snapshots_coverage_nonnegative"),
        ),
        sa.CheckConstraint(
            "expiring_quantity >= 0 AND expiring_quantity <= physical_verified_quantity",
            name=op.f("ck_reserve_snapshots_expiring_bounded"),
        ),
        sa.CheckConstraint(
            "jsonb_array_length(evidence_ids) > 0",
            name=op.f("ck_reserve_snapshots_evidence_required"),
        ),
        sa.CheckConstraint(
            "physical_verified_quantity >= 0",
            name=op.f("ck_reserve_snapshots_verified_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_reserve_snapshots_recorded_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_reserve_snapshots_recorded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_reserve_snapshots_recorded_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_reserve_snapshots_recorded_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["solidarity.reserve_targets.id"],
            name=op.f("fk_reserve_snapshots_target_id_reserve_targets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reserve_snapshots")),
        sa.UniqueConstraint(
            "recorded_event_id", name=op.f("uq_reserve_snapshots_recorded_event_id")
        ),
        schema="solidarity",
    )
    op.create_index(
        "ix_reserve_snapshots_target_observed",
        "reserve_snapshots",
        ["target_id", "observed_at"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "rationing_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("available_input", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("eligible_count", sa.Integer(), nullable=False),
        sa.Column("total_allocated", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("eligibility_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("allocations_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_by_member_id", sa.UUID(), nullable=False),
        sa.Column("proposed_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("preview_event_id", sa.UUID(), nullable=False),
        sa.Column("confirmed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_by_member_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_role_assignment_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "allocations_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_rationing_plans_allocations_hash_sha256"),
        ),
        sa.CheckConstraint(
            "input_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_rationing_plans_input_hash_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('PREVIEWED','CONFIRMED','CANCELLED','EXPIRED')",
            name=op.f("ck_rationing_plans_status_allowed"),
        ),
        sa.CheckConstraint(
            "available_input >= 0 AND total_allocated >= 0 AND total_allocated <= available_input",
            name=op.f("ck_rationing_plans_totals_bounded"),
        ),
        sa.CheckConstraint(
            "eligible_count > 0", name=op.f("ck_rationing_plans_eligible_count_positive")
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_rationing_plans_expiry_after_creation")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_rationing_plans_version_positive")),
        sa.ForeignKeyConstraint(
            ["confirmed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rationing_plans_confirmed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_rationing_plans_confirmed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rationing_plans_confirmed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_rationing_plans_confirmed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["preview_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rationing_plans_preview_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_rationing_plans_proposed_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_rationing_plans_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_rationing_plans_proposed_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["solidarity.rationing_rules.id"],
            name=op.f("fk_rationing_plans_rule_id_rationing_rules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["solidarity.reserve_snapshots.id"],
            name=op.f("fk_rationing_plans_snapshot_id_reserve_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rationing_plans")),
        sa.UniqueConstraint(
            "confirmed_event_id", name=op.f("uq_rationing_plans_confirmed_event_id")
        ),
        sa.UniqueConstraint("preview_event_id", name=op.f("uq_rationing_plans_preview_event_id")),
        schema="solidarity",
    )
    op.create_index(
        "ix_rationing_plans_rule_status",
        "rationing_plans",
        ["rule_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "rationing_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("issued_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PROPOSED','RESERVED','ISSUED','CANCELLED')",
            name=op.f("ck_rationing_allocations_status_allowed"),
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_rationing_allocations_quantity_nonnegative")
        ),
        sa.CheckConstraint(
            "weight BETWEEN 1 AND 100", name=op.f("ck_rationing_allocations_weight_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["issued_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_rationing_allocations_issued_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_rationing_allocations_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["solidarity.rationing_plans.id"],
            name=op.f("fk_rationing_allocations_plan_id_rationing_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rationing_allocations")),
        sa.UniqueConstraint(
            "issued_event_id", name=op.f("uq_rationing_allocations_issued_event_id")
        ),
        sa.UniqueConstraint("plan_id", "member_id", name="uq_rationing_allocation_member"),
        schema="solidarity",
    )
    op.create_index(
        "ix_rationing_allocations_member",
        "rationing_allocations",
        ["member_id", "status"],
        unique=False,
        schema="solidarity",
    )
    op.create_table(
        "ration_issuances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("allocation_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("acknowledgement", sa.Text(), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("issued_by_user_id", sa.UUID(), nullable=False),
        sa.Column("issued_by_member_id", sa.UUID(), nullable=False),
        sa.Column("issued_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_array_length(evidence_ids) > 0",
            name=op.f("ck_ration_issuances_evidence_required"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_ration_issuances_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["solidarity.rationing_allocations.id"],
            name=op.f("fk_ration_issuances_allocation_id_rationing_allocations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_ration_issuances_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_ration_issuances_issued_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_ration_issuances_issued_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_ration_issuances_issued_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ration_issuances")),
        sa.UniqueConstraint("allocation_id", name="uq_ration_issuance_allocation"),
        sa.UniqueConstraint("event_id", name=op.f("uq_ration_issuances_event_id")),
        schema="solidarity",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION solidarity.prevent_crisis_immutable_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'crisis snapshot, review, issuance, and report records are append-only';
        END;
        $$;
        CREATE TRIGGER trg_reserve_snapshots_append_only
          BEFORE UPDATE OR DELETE ON solidarity.reserve_snapshots
          FOR EACH ROW EXECUTE FUNCTION solidarity.prevent_crisis_immutable_mutation();
        CREATE TRIGGER trg_crisis_reviews_append_only
          BEFORE UPDATE OR DELETE ON solidarity.crisis_reviews
          FOR EACH ROW EXECUTE FUNCTION solidarity.prevent_crisis_immutable_mutation();
        CREATE TRIGGER trg_ration_issuances_append_only
          BEFORE UPDATE OR DELETE ON solidarity.ration_issuances
          FOR EACH ROW EXECUTE FUNCTION solidarity.prevent_crisis_immutable_mutation();
        CREATE TRIGGER trg_crisis_reports_append_only
          BEFORE UPDATE OR DELETE ON solidarity.crisis_reports
          FOR EACH ROW EXECUTE FUNCTION solidarity.prevent_crisis_immutable_mutation();
        """
    )
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT SELECT, INSERT, UPDATE ON solidarity.crisis_mandates,
              solidarity.reserve_targets, solidarity.crisis_paper_forms,
              solidarity.rationing_rules, solidarity.rationing_plans,
              solidarity.rationing_allocations TO coop_app;
            GRANT SELECT, INSERT ON solidarity.reserve_snapshots,
              solidarity.crisis_reviews, solidarity.ration_issuances,
              solidarity.crisis_reports TO coop_app;
            REVOKE DELETE ON ALL TABLES IN SCHEMA solidarity FROM coop_app;
            REVOKE UPDATE ON solidarity.reserve_snapshots,
              solidarity.crisis_reviews, solidarity.ration_issuances,
              solidarity.crisis_reports FROM coop_app;
          END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM solidarity.crisis_mandates)
             OR EXISTS (SELECT 1 FROM solidarity.reserve_targets)
             OR EXISTS (SELECT 1 FROM solidarity.reserve_snapshots)
             OR EXISTS (SELECT 1 FROM solidarity.rationing_rules)
             OR EXISTS (SELECT 1 FROM solidarity.rationing_plans)
             OR EXISTS (SELECT 1 FROM solidarity.rationing_allocations)
             OR EXISTS (SELECT 1 FROM solidarity.ration_issuances)
             OR EXISTS (SELECT 1 FROM solidarity.crisis_paper_forms)
             OR EXISTS (SELECT 1 FROM solidarity.crisis_reviews)
             OR EXISTS (SELECT 1 FROM solidarity.crisis_reports)
             OR EXISTS (
               SELECT 1 FROM identity.role_assignments
               WHERE role_code IN ('CRISIS_OPERATOR','CRISIS_CONTROLLER')
             ) THEN
            RAISE EXCEPTION 'cannot downgrade 0012: crisis records or roles would be lost';
          END IF;
        END
        $$;
        """
    )
    op.execute("DROP FUNCTION IF EXISTS solidarity.prevent_crisis_immutable_mutation CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ration_issuances", schema="solidarity")
    op.drop_index(
        "ix_rationing_allocations_member", table_name="rationing_allocations", schema="solidarity"
    )
    op.drop_table("rationing_allocations", schema="solidarity")
    op.drop_index(
        "ix_rationing_plans_rule_status", table_name="rationing_plans", schema="solidarity"
    )
    op.drop_table("rationing_plans", schema="solidarity")
    op.drop_index(
        "ix_reserve_snapshots_target_observed", table_name="reserve_snapshots", schema="solidarity"
    )
    op.drop_table("reserve_snapshots", schema="solidarity")
    op.drop_table("rationing_rules", schema="solidarity")
    op.drop_table("crisis_reviews", schema="solidarity")
    op.drop_table("crisis_reports", schema="solidarity")
    op.drop_table("crisis_paper_forms", schema="solidarity")
    op.drop_index("ix_reserve_targets_active", table_name="reserve_targets", schema="solidarity")
    op.drop_table("reserve_targets", schema="solidarity")
    op.drop_index("ix_crisis_mandates_status", table_name="crisis_mandates", schema="solidarity")
    op.drop_table("crisis_mandates", schema="solidarity")
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SOLIDARITY_OPERATOR','SOLIDARITY_CONTROLLER',
              'SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR','ARBITRATOR'
            )
          );
        """
    )
    # ### end Alembic commands ###
