"""offline node federation

Revision ID: 0013_offline_nodes
Revises: 0012_crisis_reserves
Create Date: 2026-07-21 16:52:06.228958
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013_offline_nodes"
down_revision: str | None = "0012_crisis_reserves"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS federation")
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SOLIDARITY_OPERATOR','SOLIDARITY_CONTROLLER',
              'CRISIS_OPERATOR','CRISIS_CONTROLLER','SECURITY_ADMIN','NODE_REGISTRAR',
              'NODE_TECHNICAL_CUSTODIAN','NODE_SECURITY_ADMIN',
              'NODE_BUSINESS_OPERATOR','NODE_AUDITOR','AUDITOR','ARBITRATOR'
            )
          );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_owner_organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("legal_name", sa.String(length=240), nullable=False),
        sa.Column("registration_code", sa.String(length=120), nullable=False),
        sa.Column("jurisdiction", sa.String(length=120), nullable=False),
        sa.Column("contact_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED','ARCHIVED')",
            name=op.f("ck_node_owner_organizations_status_allowed"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_node_owner_organizations_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_owner_organizations_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_owner_organizations")),
        sa.UniqueConstraint(
            "created_event_id", name=op.f("uq_node_owner_organizations_created_event_id")
        ),
        sa.UniqueConstraint("jurisdiction", "registration_code", name="uq_node_owner_registration"),
        schema="federation",
    )
    op.create_table(
        "external_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_code", sa.String(length=63), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("owner_organization_id", sa.UUID(), nullable=False),
        sa.Column("sponsor_local_node_id", sa.UUID(), nullable=False),
        sa.Column("territory", sa.String(length=160), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trust_level", sa.String(length=16), nullable=False),
        sa.Column("network_endpoints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hardware_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("release_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("supported_protocols", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("supported_policies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checkpoint_hash", sa.String(length=71), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','APPLICATION_SUBMITTED','IDENTITY_VERIFIED','TECHNICAL_CHALLENGE','AUDIT_PENDING','LIMITED','ACTIVE','SUSPENDED','QUARANTINED','REVOKED','ARCHIVED','REJECTED')",
            name=op.f("ck_external_nodes_status_allowed"),
        ),
        sa.CheckConstraint(
            "trust_level IN ('UNTRUSTED','LIMITED','STANDARD','HIGH')",
            name=op.f("ck_external_nodes_trust_level_allowed"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_external_nodes_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_external_nodes_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"],
            ["federation.node_owner_organizations.id"],
            name=op.f("fk_external_nodes_owner_organization_id_node_owner_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_local_node_id"],
            ["node.node_profiles.id"],
            name=op.f("fk_external_nodes_sponsor_local_node_id_node_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_nodes")),
        sa.UniqueConstraint("created_event_id", name=op.f("uq_external_nodes_created_event_id")),
        sa.UniqueConstraint("node_code", name=op.f("uq_external_nodes_node_code")),
        schema="federation",
    )
    op.create_index(
        "ix_external_nodes_owner_status",
        "external_nodes",
        ["owner_organization_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "offline_epochs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("local_node_id", sa.UUID(), nullable=True),
        sa.Column("external_node_id", sa.UUID(), nullable=True),
        sa.Column("base_checkpoint_hash", sa.String(length=71), nullable=True),
        sa.Column("allowed_event_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("policy_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("emergency_contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("closure_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column("opened_event_id", sa.UUID(), nullable=False),
        sa.Column("closed_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "policy_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_offline_epochs_policy_hash_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','OPEN','CLOSED','EXPIRED','REVOKED')",
            name=op.f("ck_offline_epochs_status_allowed"),
        ),
        sa.CheckConstraint(
            "(local_node_id IS NOT NULL AND external_node_id IS NULL) OR (local_node_id IS NULL AND external_node_id IS NOT NULL)",
            name=op.f("ck_offline_epochs_one_node_subject"),
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > starts_at",
            name=op.f("ck_offline_epochs_period_valid"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_offline_epochs_version_positive")),
        sa.ForeignKeyConstraint(
            ["closed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_offline_epochs_closed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["external_node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_offline_epochs_external_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["local_node_id"],
            ["node.node_profiles.id"],
            name=op.f("fk_offline_epochs_local_node_id_node_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_offline_epochs_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_offline_epochs_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offline_epochs")),
        sa.UniqueConstraint("closed_event_id", name=op.f("uq_offline_epochs_closed_event_id")),
        sa.UniqueConstraint("opened_event_id", name=op.f("uq_offline_epochs_opened_event_id")),
        schema="federation",
    )
    op.create_index(
        "ix_offline_epochs_external_status",
        "offline_epochs",
        ["external_node_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "node_bonds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("provider_organization_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=160), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("protected_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("maximum_loss", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("capability_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PLEDGED','ACTIVE','FROZEN','RELEASED','EXHAUSTED')",
            name=op.f("ck_node_bonds_status_allowed"),
        ),
        sa.CheckConstraint(
            "amount > 0 AND protected_amount >= 0 AND protected_amount < amount",
            name=op.f("ck_node_bonds_amount_valid"),
        ),
        sa.CheckConstraint(
            "maximum_loss > 0 AND maximum_loss <= amount - protected_amount",
            name=op.f("ck_node_bonds_loss_bounded"),
        ),
        sa.CheckConstraint("valid_until > valid_from", name=op.f("ck_node_bonds_period_valid")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_bonds_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_bonds_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_organization_id"],
            ["federation.node_owner_organizations.id"],
            name=op.f("fk_node_bonds_provider_organization_id_node_owner_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_bonds")),
        sa.UniqueConstraint("event_id", name=op.f("uq_node_bonds_event_id")),
        sa.UniqueConstraint("reference", name=op.f("uq_node_bonds_reference")),
        schema="federation",
    )
    op.create_index(
        "ix_node_bonds_node_status",
        "node_bonds",
        ["node_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "node_certificates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("algorithm", sa.String(length=20), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("fingerprint", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_event_id", sa.UUID(), nullable=True),
        sa.Column("revoked_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "algorithm = 'Ed25519'", name=op.f("ck_node_certificates_algorithm_allowed")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','ACTIVE','ROTATING','RETIRED','SUSPENDED','REVOKED','COMPROMISED')",
            name=op.f("ck_node_certificates_status_allowed"),
        ),
        sa.CheckConstraint(
            "valid_until > valid_from", name=op.f("ck_node_certificates_period_valid")
        ),
        sa.ForeignKeyConstraint(
            ["activated_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_certificates_activated_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_certificates_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_certificates_revoked_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_certificates")),
        sa.UniqueConstraint(
            "activated_event_id", name=op.f("uq_node_certificates_activated_event_id")
        ),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_node_certificates_fingerprint")),
        sa.UniqueConstraint("revoked_event_id", name=op.f("uq_node_certificates_revoked_event_id")),
        schema="federation",
    )
    op.create_index(
        "ix_node_certificates_node_status",
        "node_certificates",
        ["node_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_index(
        "uq_node_certificate_active",
        "node_certificates",
        ["node_id"],
        unique=True,
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "node_exposures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("capability", sa.String(length=40), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("reserved_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("updated_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "current_amount >= 0 AND reserved_amount >= 0",
            name=op.f("ck_node_exposures_amounts_nonnegative"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_node_exposures_version_positive")),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_exposures_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_exposures_updated_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_exposures")),
        sa.UniqueConstraint(
            "node_id", "capability", "unit", name="uq_node_exposure_capability_unit"
        ),
        schema="federation",
    )
    op.create_table(
        "node_bilateral_limits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("capability", sa.String(length=40), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("max_package_value", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_unsettled_obligations", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_external_rights", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_clearing_position", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_offline_hours", sa.Integer(), nullable=False),
        sa.Column(
            "allowed_critical_resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("required_confirmations", sa.Integer(), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','RETIRED')",
            name=op.f("ck_node_bilateral_limits_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_node_bilateral_limits_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "max_offline_hours > 0 AND required_confirmations > 0",
            name=op.f("ck_node_bilateral_limits_limits_positive"),
        ),
        sa.CheckConstraint(
            "max_package_value >= 0 AND max_unsettled_obligations >= 0 AND max_external_rights >= 0 AND max_clearing_position >= 0",
            name=op.f("ck_node_bilateral_limits_amounts_nonnegative"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_node_bilateral_limits_version_positive")),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_bilateral_limits_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_bilateral_limits_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_bilateral_limits_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_bilateral_limits_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_bilateral_limits_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_bilateral_limits")),
        sa.UniqueConstraint(
            "approved_event_id", name=op.f("uq_node_bilateral_limits_approved_event_id")
        ),
        sa.UniqueConstraint(
            "proposed_event_id", name=op.f("uq_node_bilateral_limits_proposed_event_id")
        ),
        schema="federation",
    )
    op.create_index(
        "uq_bilateral_limit_active_capability",
        "node_bilateral_limits",
        ["node_id", "capability"],
        unique=True,
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "node_key_rotation_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("old_certificate_id", sa.UUID(), nullable=False),
        sa.Column("new_certificate_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=False),
        sa.Column("requested_event_id", sa.UUID(), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("decided_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "continuity_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "reason IN ('SCHEDULED','COMPROMISE','CUSTODY_CHANGE','RECOVERY')",
            name=op.f("ck_node_key_rotation_requests_reason_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','APPROVED','REJECTED','CANCELLED')",
            name=op.f("ck_node_key_rotation_requests_status_allowed"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_node_key_rotation_requests_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_key_rotation_requests_decided_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_key_rotation_requests_decided_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["new_certificate_id"],
            ["federation.node_certificates.id"],
            name=op.f("fk_node_key_rotation_requests_new_certificate_id_node_certificates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_key_rotation_requests_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["old_certificate_id"],
            ["federation.node_certificates.id"],
            name=op.f("fk_node_key_rotation_requests_old_certificate_id_node_certificates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_key_rotation_requests_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_key_rotation_requests_requested_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_key_rotation_requests")),
        sa.UniqueConstraint(
            "decided_event_id", name=op.f("uq_node_key_rotation_requests_decided_event_id")
        ),
        sa.UniqueConstraint(
            "requested_event_id", name=op.f("uq_node_key_rotation_requests_requested_event_id")
        ),
        schema="federation",
    )
    op.create_index(
        "ix_node_key_rotations_node_status",
        "node_key_rotation_requests",
        ["node_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "node_security_incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("incident_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("earliest_compromise_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("containment_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrective_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opened_by_user_id", sa.UUID(), nullable=False),
        sa.Column("opened_event_id", sa.UUID(), nullable=False),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "severity IN ('LOW','MEDIUM','HIGH','CRITICAL')",
            name=op.f("ck_node_security_incidents_severity_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','CONTAINED','RESOLVED','APPEALED')",
            name=op.f("ck_node_security_incidents_status_allowed"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_node_security_incidents_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_security_incidents_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_security_incidents_opened_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_security_incidents_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_security_incidents_resolved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_security_incidents_resolved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_security_incidents")),
        sa.UniqueConstraint(
            "opened_event_id", name=op.f("uq_node_security_incidents_opened_event_id")
        ),
        sa.UniqueConstraint(
            "resolved_event_id", name=op.f("uq_node_security_incidents_resolved_event_id")
        ),
        schema="federation",
    )
    op.create_index(
        "ix_node_security_incidents_node_status",
        "node_security_incidents",
        ["node_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "sync_packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("peer_node_id", sa.UUID(), nullable=False),
        sa.Column("epoch_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_node_code", sa.String(length=63), nullable=False),
        sa.Column("target_node_code", sa.String(length=63), nullable=False),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("required_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sequence_first", sa.Integer(), nullable=False),
        sa.Column("sequence_last", sa.Integer(), nullable=False),
        sa.Column("base_checkpoint_hash", sa.String(length=71), nullable=True),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("blob_count", sa.Integer(), nullable=False),
        sa.Column("archive_size", sa.Integer(), nullable=False),
        sa.Column("archive_hash", sa.String(length=71), nullable=False),
        sa.Column("manifest_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manifest_hash", sa.String(length=71), nullable=False),
        sa.Column("archive_path", sa.String(length=500), nullable=False),
        sa.Column("simulation_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rejection_code", sa.String(length=100), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("applied_by_user_id", sa.UUID(), nullable=True),
        sa.Column("applied_event_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("simulated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "archive_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_sync_packages_archive_hash_sha256"),
        ),
        sa.CheckConstraint(
            "direction IN ('INBOUND','OUTBOUND')", name=op.f("ck_sync_packages_direction_allowed")
        ),
        sa.CheckConstraint(
            "manifest_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_sync_packages_manifest_hash_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('EXPORTED','QUARANTINED','VERIFIED','SIMULATED','CONFLICT','APPLIED','REJECTED')",
            name=op.f("ck_sync_packages_status_allowed"),
        ),
        sa.CheckConstraint(
            "event_count > 0 AND blob_count >= 0 AND archive_size > 0",
            name=op.f("ck_sync_packages_counts_positive"),
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_sync_packages_period_valid")),
        sa.CheckConstraint(
            "sequence_first > 0 AND sequence_last >= sequence_first",
            name=op.f("ck_sync_packages_sequence_valid"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_sync_packages_version_positive")),
        sa.ForeignKeyConstraint(
            ["applied_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_sync_packages_applied_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["applied_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sync_packages_applied_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_sync_packages_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sync_packages_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["epoch_id"],
            ["federation.offline_epochs.id"],
            name=op.f("fk_sync_packages_epoch_id_offline_epochs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["peer_node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_sync_packages_peer_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_packages")),
        sa.UniqueConstraint("applied_event_id", name=op.f("uq_sync_packages_applied_event_id")),
        sa.UniqueConstraint("created_event_id", name=op.f("uq_sync_packages_created_event_id")),
        schema="federation",
    )
    op.create_index(
        "ix_sync_packages_peer_status",
        "sync_packages",
        ["peer_node_id", "status", "created_at"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "federation_checkpoints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("peer_node_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("local_sequence", sa.Integer(), nullable=False),
        sa.Column("remote_sequence", sa.Integer(), nullable=False),
        sa.Column("local_event_hash", sa.String(length=71), nullable=True),
        sa.Column("remote_event_hash", sa.String(length=71), nullable=True),
        sa.Column("checkpoint_hash", sa.String(length=71), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checkpoint_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federation_checkpoints_checkpoint_hash_sha256"),
        ),
        sa.CheckConstraint(
            "local_sequence >= 0 AND remote_sequence >= 0",
            name=op.f("ck_federation_checkpoints_sequences_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federation_checkpoints_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["federation.sync_packages.id"],
            name=op.f("fk_federation_checkpoints_package_id_sync_packages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["peer_node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_federation_checkpoints_peer_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federation_checkpoints")),
        sa.UniqueConstraint("event_id", name=op.f("uq_federation_checkpoints_event_id")),
        sa.UniqueConstraint(
            "peer_node_id", "checkpoint_hash", name="uq_federation_checkpoint_hash"
        ),
        schema="federation",
    )
    op.create_index(
        "ix_federation_checkpoints_peer_created",
        "federation_checkpoints",
        ["peer_node_id", "created_at"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "inbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("source_node_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("local_sequence", sa.Integer(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("previous_event_hash", sa.String(length=71), nullable=True),
        sa.Column("event_hash", sa.String(length=71), nullable=False),
        sa.Column("envelope_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signature", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("effect_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "event_hash ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_inbox_events_event_hash_sha256")
        ),
        sa.CheckConstraint(
            "status IN ('HELD','READY','APPLIED','IGNORED','REJECTED','CONFLICT')",
            name=op.f("ck_inbox_events_status_allowed"),
        ),
        sa.CheckConstraint(
            "local_sequence > 0 AND aggregate_version > 0",
            name=op.f("ck_inbox_events_versions_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["federation.sync_packages.id"],
            name=op.f("fk_inbox_events_package_id_sync_packages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_inbox_events_source_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_events")),
        sa.UniqueConstraint("source_node_id", "event_id", name="uq_inbox_source_event"),
        sa.UniqueConstraint("source_node_id", "local_sequence", name="uq_inbox_source_sequence"),
        schema="federation",
    )
    op.create_index(
        "ix_inbox_events_aggregate",
        "inbox_events",
        ["aggregate_type", "aggregate_id", "aggregate_version"],
        unique=False,
        schema="federation",
    )
    op.create_index(
        "ix_inbox_events_package_status",
        "inbox_events",
        ["package_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "node_applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("requested_limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_data_scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recovery_contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "security_questionnaire", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_trust_expiry", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_member_id", sa.UUID(), nullable=False),
        sa.Column("created_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("identity_verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("identity_verified_event_id", sa.UUID(), nullable=True),
        sa.Column("audit_decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("audit_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("identity_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audit_decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','APPLICATION_SUBMITTED','IDENTITY_VERIFIED','TECHNICAL_CHALLENGE','AUDIT_PENDING','LIMITED','ACTIVE','REJECTED')",
            name=op.f("ck_node_applications_status_allowed"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_node_applications_version_positive")),
        sa.ForeignKeyConstraint(
            ["audit_decided_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_applications_audit_decided_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["audit_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_applications_audit_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_node_applications_created_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_applications_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_applications_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_node_applications_created_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["identity_verified_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_applications_identity_verified_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["identity_verified_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_applications_identity_verified_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_applications_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_applications")),
        sa.UniqueConstraint("audit_event_id", name=op.f("uq_node_applications_audit_event_id")),
        sa.UniqueConstraint("created_event_id", name=op.f("uq_node_applications_created_event_id")),
        sa.UniqueConstraint(
            "identity_verified_event_id",
            name=op.f("uq_node_applications_identity_verified_event_id"),
        ),
        schema="federation",
    )
    op.create_index(
        "ix_node_applications_status",
        "node_applications",
        ["status", "created_at"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "sync_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("receipt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("receipt_hash", sa.String(length=71), nullable=False),
        sa.Column("signature", sa.LargeBinary(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "receipt_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_sync_receipts_receipt_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sync_receipts_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["federation.sync_packages.id"],
            name=op.f("fk_sync_receipts_package_id_sync_packages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_receipts")),
        sa.UniqueConstraint("event_id", name=op.f("uq_sync_receipts_event_id")),
        sa.UniqueConstraint("package_id", name="uq_sync_receipt_package"),
        schema="federation",
    )
    op.create_table(
        "node_challenges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("certificate_id", sa.UUID(), nullable=False),
        sa.Column("nonce_hash", sa.String(length=71), nullable=False),
        sa.Column("challenge_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("issued_by_user_id", sa.UUID(), nullable=False),
        sa.Column("issued_event_id", sa.UUID(), nullable=False),
        sa.Column("response_signature", sa.LargeBinary(), nullable=True),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_event_id", sa.UUID(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "nonce_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_node_challenges_nonce_hash_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('ISSUED','PASSED','FAILED','EXPIRED')",
            name=op.f("ck_node_challenges_status_allowed"),
        ),
        sa.CheckConstraint("expires_at > issued_at", name=op.f("ck_node_challenges_period_valid")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["federation.node_applications.id"],
            name=op.f("fk_node_challenges_application_id_node_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["federation.node_certificates.id"],
            name=op.f("fk_node_challenges_certificate_id_node_certificates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_challenges_issued_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_challenges_issued_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["response_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_challenges_response_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_challenges")),
        sa.UniqueConstraint("issued_event_id", name=op.f("uq_node_challenges_issued_event_id")),
        sa.UniqueConstraint("response_event_id", name=op.f("uq_node_challenges_response_event_id")),
        schema="federation",
    )
    op.create_index(
        "ix_node_challenges_application",
        "node_challenges",
        ["application_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "node_responsible_parties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("role_code", sa.String(length=40), nullable=False),
        sa.Column("capability_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("responsibility_scope", sa.Text(), nullable=False),
        sa.Column("max_exposure", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("exposure_unit", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_event_id", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role_code IN ('OWNER_SIGNATORY','TECHNICAL_CUSTODIAN','SECURITY_ADMINISTRATOR','BUSINESS_OPERATOR','NODE_AUDITOR','SPONSOR_APPROVER')",
            name=op.f("ck_node_responsible_parties_role_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','ACTIVE','RELEASED','REVOKED')",
            name=op.f("ck_node_responsible_parties_status_allowed"),
        ),
        sa.CheckConstraint(
            "max_exposure >= 0", name=op.f("ck_node_responsible_parties_exposure_nonnegative")
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name=op.f("ck_node_responsible_parties_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_responsible_parties_accepted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_responsible_parties_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["federation.node_applications.id"],
            name=op.f("fk_node_responsible_parties_application_id_node_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["identity.members.id"],
            name=op.f("fk_node_responsible_parties_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_responsible_parties_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_node_responsible_parties_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_responsible_parties")),
        sa.UniqueConstraint(
            "accepted_event_id", name=op.f("uq_node_responsible_parties_accepted_event_id")
        ),
        schema="federation",
    )
    op.create_index(
        "ix_node_responsible_node_status",
        "node_responsible_parties",
        ["node_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_index(
        "uq_node_responsible_active_role_member",
        "node_responsible_parties",
        ["node_id", "role_code", "member_id"],
        unique=True,
        schema="federation",
        postgresql_where=sa.text("status IN ('PROPOSED','ACTIVE')"),
    )
    op.create_table(
        "node_trust_contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("contract_number", sa.String(length=80), nullable=False),
        sa.Column("trust_level", sa.String(length=16), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inbound_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outbound_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("federation_limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "allowed_counterparties", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("max_offline_hours", sa.Integer(), nullable=False),
        sa.Column("required_protocols", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_policies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("service_levels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("liability_terms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terms_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("proposed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("proposed_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','EXPIRED','REVOKED')",
            name=op.f("ck_node_trust_contracts_status_allowed"),
        ),
        sa.CheckConstraint(
            "terms_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_node_trust_contracts_terms_hash_sha256"),
        ),
        sa.CheckConstraint(
            "trust_level IN ('LIMITED','STANDARD','HIGH')",
            name=op.f("ck_node_trust_contracts_trust_level_allowed"),
        ),
        sa.CheckConstraint(
            "max_offline_hours > 0", name=op.f("ck_node_trust_contracts_offline_positive")
        ),
        sa.CheckConstraint(
            "valid_until > valid_from", name=op.f("ck_node_trust_contracts_period_valid")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_node_trust_contracts_version_positive")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["federation.node_applications.id"],
            name=op.f("fk_node_trust_contracts_application_id_node_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_trust_contracts_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_trust_contracts_approved_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["federation.external_nodes.id"],
            name=op.f("fk_node_trust_contracts_node_id_external_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_node_trust_contracts_proposed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_trust_contracts_proposed_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_trust_contracts")),
        sa.UniqueConstraint(
            "approved_event_id", name=op.f("uq_node_trust_contracts_approved_event_id")
        ),
        sa.UniqueConstraint(
            "contract_number", name=op.f("uq_node_trust_contracts_contract_number")
        ),
        sa.UniqueConstraint(
            "proposed_event_id", name=op.f("uq_node_trust_contracts_proposed_event_id")
        ),
        schema="federation",
    )
    op.create_index(
        "uq_node_trust_contract_active",
        "node_trust_contracts",
        ["node_id"],
        unique=True,
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "sync_conflicts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("inbox_event_id", sa.UUID(), nullable=True),
        sa.Column("conflict_class", sa.String(length=40), nullable=False),
        sa.Column("affected_object_type", sa.String(length=100), nullable=False),
        sa.Column("affected_object_id", sa.UUID(), nullable=True),
        sa.Column("local_event_id", sa.UUID(), nullable=True),
        sa.Column("remote_event_id", sa.UUID(), nullable=True),
        sa.Column("local_event_hash", sa.String(length=71), nullable=True),
        sa.Column("remote_event_hash", sa.String(length=71), nullable=True),
        sa.Column("maximum_exposure", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("exposure_unit", sa.String(length=32), nullable=False),
        sa.Column("freeze_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("opened_event_id", sa.UUID(), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("decided_event_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "conflict_class IN ('DUPLICATE','TAMPERED_DUPLICATE','REFERENTIAL_GAP','CONCURRENT_METADATA','COMPETING_RESERVATION','DOUBLE_REDEMPTION','ROLE_KEY_INVALID','POLICY_MISMATCH','CUSTODY_CONFLICT','REPUTATION_DIVERGENCE')",
            name=op.f("ck_sync_conflicts_class_allowed"),
        ),
        sa.CheckConstraint(
            "decision IS NULL OR decision IN ('ACCEPT_REMOTE','KEEP_LOCAL','COMPENSATE','REJECT_PACKAGE')",
            name=op.f("ck_sync_conflicts_decision_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','UNDER_REVIEW','RESOLVED','APPEALED')",
            name=op.f("ck_sync_conflicts_status_allowed"),
        ),
        sa.CheckConstraint(
            "maximum_exposure >= 0", name=op.f("ck_sync_conflicts_exposure_nonnegative")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_sync_conflicts_version_positive")),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_sync_conflicts_decided_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sync_conflicts_decided_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inbox_event_id"],
            ["federation.inbox_events.id"],
            name=op.f("fk_sync_conflicts_inbox_event_id_inbox_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_sync_conflicts_opened_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["federation.sync_packages.id"],
            name=op.f("fk_sync_conflicts_package_id_sync_packages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_conflicts")),
        sa.UniqueConstraint("decided_event_id", name=op.f("uq_sync_conflicts_decided_event_id")),
        sa.UniqueConstraint("opened_event_id", name=op.f("uq_sync_conflicts_opened_event_id")),
        schema="federation",
    )
    op.create_index(
        "ix_sync_conflicts_status",
        "sync_conflicts",
        ["status", "created_at"],
        unique=False,
        schema="federation",
    )
    op.add_column(
        "signed_events", sa.Column("offline_epoch_id", sa.UUID(), nullable=True), schema="journal"
    )
    op.create_foreign_key(
        op.f("fk_signed_events_offline_epoch_id_offline_epochs"),
        "signed_events",
        "offline_epochs",
        ["offline_epoch_id"],
        ["id"],
        source_schema="journal",
        referent_schema="federation",
        ondelete="RESTRICT",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION federation.prevent_sync_evidence_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'federation receipt and checkpoint records are append-only';
        END;
        $$;
        CREATE TRIGGER trg_sync_receipts_append_only
          BEFORE UPDATE OR DELETE ON federation.sync_receipts
          FOR EACH ROW EXECUTE FUNCTION federation.prevent_sync_evidence_mutation();
        CREATE TRIGGER trg_federation_checkpoints_append_only
          BEFORE UPDATE OR DELETE ON federation.federation_checkpoints
          FOR EACH ROW EXECUTE FUNCTION federation.prevent_sync_evidence_mutation();

        CREATE OR REPLACE FUNCTION federation.protect_inbox_event_evidence()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' OR
             OLD.id IS DISTINCT FROM NEW.id OR
             OLD.package_id IS DISTINCT FROM NEW.package_id OR
             OLD.source_node_id IS DISTINCT FROM NEW.source_node_id OR
             OLD.event_id IS DISTINCT FROM NEW.event_id OR
             OLD.event_type IS DISTINCT FROM NEW.event_type OR
             OLD.local_sequence IS DISTINCT FROM NEW.local_sequence OR
             OLD.aggregate_type IS DISTINCT FROM NEW.aggregate_type OR
             OLD.aggregate_id IS DISTINCT FROM NEW.aggregate_id OR
             OLD.aggregate_version IS DISTINCT FROM NEW.aggregate_version OR
             OLD.previous_event_hash IS DISTINCT FROM NEW.previous_event_hash OR
             OLD.event_hash IS DISTINCT FROM NEW.event_hash OR
             OLD.envelope_payload IS DISTINCT FROM NEW.envelope_payload OR
             OLD.signature IS DISTINCT FROM NEW.signature OR
             OLD.effect_summary IS DISTINCT FROM NEW.effect_summary OR
             OLD.received_at IS DISTINCT FROM NEW.received_at THEN
            RAISE EXCEPTION 'imported federation event evidence is immutable';
          END IF;
          RETURN NEW;
        END;
        $$;
        CREATE TRIGGER trg_inbox_events_evidence_protected
          BEFORE UPDATE OR DELETE ON federation.inbox_events
          FOR EACH ROW EXECUTE FUNCTION federation.protect_inbox_event_evidence();
        """
    )
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT USAGE ON SCHEMA federation TO coop_app;
            GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA federation TO coop_app;
            REVOKE DELETE ON ALL TABLES IN SCHEMA federation FROM coop_app;
            REVOKE UPDATE ON federation.sync_receipts,
              federation.federation_checkpoints FROM coop_app;
          END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM federation.external_nodes)
             OR EXISTS (SELECT 1 FROM federation.node_owner_organizations)
             OR EXISTS (SELECT 1 FROM federation.offline_epochs)
             OR EXISTS (SELECT 1 FROM federation.node_bonds)
             OR EXISTS (SELECT 1 FROM federation.node_certificates)
             OR EXISTS (SELECT 1 FROM federation.node_exposures)
             OR EXISTS (SELECT 1 FROM federation.node_bilateral_limits)
             OR EXISTS (SELECT 1 FROM federation.node_key_rotation_requests)
             OR EXISTS (SELECT 1 FROM federation.node_security_incidents)
             OR EXISTS (SELECT 1 FROM federation.sync_packages)
             OR EXISTS (SELECT 1 FROM federation.federation_checkpoints)
             OR EXISTS (SELECT 1 FROM federation.inbox_events)
             OR EXISTS (SELECT 1 FROM federation.node_applications)
             OR EXISTS (SELECT 1 FROM federation.sync_receipts)
             OR EXISTS (SELECT 1 FROM federation.node_challenges)
             OR EXISTS (SELECT 1 FROM federation.node_responsible_parties)
             OR EXISTS (SELECT 1 FROM federation.node_trust_contracts)
             OR EXISTS (SELECT 1 FROM federation.sync_conflicts)
             OR EXISTS (
               SELECT 1 FROM identity.role_assignments
               WHERE role_code IN (
                 'NODE_TECHNICAL_CUSTODIAN','NODE_SECURITY_ADMIN',
                 'NODE_BUSINESS_OPERATOR','NODE_AUDITOR'
               )
             ) THEN
            RAISE EXCEPTION 'cannot downgrade 0013: federation records or roles would be lost';
          END IF;
        END $$;
        """
    )
    op.execute("DROP FUNCTION IF EXISTS federation.protect_inbox_event_evidence CASCADE")
    op.execute("DROP FUNCTION IF EXISTS federation.prevent_sync_evidence_mutation CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_signed_events_offline_epoch_id_offline_epochs"),
        "signed_events",
        schema="journal",
        type_="foreignkey",
    )
    op.drop_column("signed_events", "offline_epoch_id", schema="journal")
    op.drop_index("ix_sync_conflicts_status", table_name="sync_conflicts", schema="federation")
    op.drop_table("sync_conflicts", schema="federation")
    op.drop_index(
        "uq_node_trust_contract_active",
        table_name="node_trust_contracts",
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("node_trust_contracts", schema="federation")
    op.drop_index(
        "uq_node_responsible_active_role_member",
        table_name="node_responsible_parties",
        schema="federation",
        postgresql_where=sa.text("status IN ('PROPOSED','ACTIVE')"),
    )
    op.drop_index(
        "ix_node_responsible_node_status",
        table_name="node_responsible_parties",
        schema="federation",
    )
    op.drop_table("node_responsible_parties", schema="federation")
    op.drop_index(
        "ix_node_challenges_application", table_name="node_challenges", schema="federation"
    )
    op.drop_table("node_challenges", schema="federation")
    op.drop_table("sync_receipts", schema="federation")
    op.drop_index(
        "ix_node_applications_status", table_name="node_applications", schema="federation"
    )
    op.drop_table("node_applications", schema="federation")
    op.drop_index("ix_inbox_events_package_status", table_name="inbox_events", schema="federation")
    op.drop_index("ix_inbox_events_aggregate", table_name="inbox_events", schema="federation")
    op.drop_table("inbox_events", schema="federation")
    op.drop_index(
        "ix_federation_checkpoints_peer_created",
        table_name="federation_checkpoints",
        schema="federation",
    )
    op.drop_table("federation_checkpoints", schema="federation")
    op.drop_index("ix_sync_packages_peer_status", table_name="sync_packages", schema="federation")
    op.drop_table("sync_packages", schema="federation")
    op.drop_index(
        "ix_node_security_incidents_node_status",
        table_name="node_security_incidents",
        schema="federation",
    )
    op.drop_table("node_security_incidents", schema="federation")
    op.drop_index(
        "ix_node_key_rotations_node_status",
        table_name="node_key_rotation_requests",
        schema="federation",
    )
    op.drop_table("node_key_rotation_requests", schema="federation")
    op.drop_index(
        "uq_bilateral_limit_active_capability",
        table_name="node_bilateral_limits",
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("node_bilateral_limits", schema="federation")
    op.drop_table("node_exposures", schema="federation")
    op.drop_index(
        "uq_node_certificate_active",
        table_name="node_certificates",
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(
        "ix_node_certificates_node_status", table_name="node_certificates", schema="federation"
    )
    op.drop_table("node_certificates", schema="federation")
    op.drop_index("ix_node_bonds_node_status", table_name="node_bonds", schema="federation")
    op.drop_table("node_bonds", schema="federation")
    op.drop_index(
        "ix_offline_epochs_external_status", table_name="offline_epochs", schema="federation"
    )
    op.drop_table("offline_epochs", schema="federation")
    op.drop_index(
        "ix_external_nodes_owner_status", table_name="external_nodes", schema="federation"
    )
    op.drop_table("external_nodes", schema="federation")
    op.drop_table("node_owner_organizations", schema="federation")
    op.execute(
        """
        ALTER TABLE identity.role_assignments
          DROP CONSTRAINT ck_role_assignments_role_allowed;
        ALTER TABLE identity.role_assignments
          ADD CONSTRAINT ck_role_assignments_role_allowed CHECK (
            role_code IN (
              'MEMBER_REGISTRAR','COOPERATIVE_ADMIN','DATA_STEWARD',
              'WAREHOUSE_CUSTODIAN','INVENTORY_CONTROLLER','LOGISTICS_OPERATOR',
              'RIGHTS_OPERATOR','RISK_ADMIN','CLEARING_OPERATOR','CLEARING_CONTROLLER',
              'CLEARING_FINALIZER','SOLIDARITY_OPERATOR','SOLIDARITY_CONTROLLER',
              'CRISIS_OPERATOR','CRISIS_CONTROLLER',
              'SECURITY_ADMIN','NODE_REGISTRAR','AUDITOR','ARBITRATOR'
            )
          );
        """
    )
    op.execute("DROP SCHEMA federation")
    # ### end Alembic commands ###
