"""inter node clearing finality

Revision ID: 0018_inter_node_clearing
Revises: 0017_peer_reservations
Create Date: 2026-07-22 00:19:40.580796
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0018_inter_node_clearing"
down_revision: str | None = "0017_peer_reservations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "federated_clearing_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("policy_code", sa.String(length=80), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("valuation_unit", sa.String(length=32), nullable=False),
        sa.Column("algorithm_id", sa.String(length=32), nullable=False),
        sa.Column("algorithm_version", sa.String(length=16), nullable=False),
        sa.Column("decimal_scale", sa.Integer(), nullable=False),
        sa.Column("rounding_mode", sa.String(length=16), nullable=False),
        sa.Column("minimum_operation", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("max_iterations", sa.Integer(), nullable=False),
        sa.Column("max_cycle_length", sa.Integer(), nullable=False),
        sa.Column("prepare_ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("policy_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_member_id", sa.UUID(), nullable=False),
        sa.Column("created_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "algorithm_id = 'FEDERATED_NETTING'",
            name=op.f("ck_federated_clearing_policies_algorithm_allowed"),
        ),
        sa.CheckConstraint(
            "algorithm_version = '1.0.0'",
            name=op.f("ck_federated_clearing_policies_algorithm_version_allowed"),
        ),
        sa.CheckConstraint(
            "policy_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_clearing_policies_policy_hash_sha256"),
        ),
        sa.CheckConstraint(
            "rounding_mode IN ('DOWN','HALF_EVEN')",
            name=op.f("ck_federated_clearing_policies_rounding_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUPERSEDED','REVOKED')",
            name=op.f("ck_federated_clearing_policies_status_allowed"),
        ),
        sa.CheckConstraint(
            "decimal_scale BETWEEN 0 AND 12",
            name=op.f("ck_federated_clearing_policies_decimal_scale_allowed"),
        ),
        sa.CheckConstraint(
            "max_cycle_length BETWEEN 3 AND 12",
            name=op.f("ck_federated_clearing_policies_cycle_length_bounded"),
        ),
        sa.CheckConstraint(
            "max_iterations BETWEEN 1 AND 100000",
            name=op.f("ck_federated_clearing_policies_iterations_bounded"),
        ),
        sa.CheckConstraint(
            "minimum_operation >= 0",
            name=op.f("ck_federated_clearing_policies_minimum_nonnegative"),
        ),
        sa.CheckConstraint(
            "policy_version >= 1 AND version >= 1",
            name=op.f("ck_federated_clearing_policies_versions_positive"),
        ),
        sa.CheckConstraint(
            "prepare_ttl_seconds BETWEEN 30 AND 86400",
            name=op.f("ck_federated_clearing_policies_prepare_ttl_bounded"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_federated_clearing_policies_created_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_federated_clearing_policies_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_clearing_policies_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_federated_clearing_policies_created_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_clearing_policies")),
        sa.UniqueConstraint(
            "created_event_id", name=op.f("uq_federated_clearing_policies_created_event_id")
        ),
        sa.UniqueConstraint("policy_code", "policy_version", name="uq_federated_policy_version"),
        schema="federation",
    )
    op.create_index(
        "uq_federated_policy_active",
        "federated_clearing_policies",
        ["policy_code"],
        unique=True,
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "federated_clearing_cycles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_code", sa.String(length=80), nullable=False),
        sa.Column("coordinator_node_code", sa.String(length=63), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "participant_node_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("affected_node_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=True),
        sa.Column("result_hash", sa.String(length=71), nullable=True),
        sa.Column("certificate_hash", sa.String(length=71), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_by_member_id", sa.UUID(), nullable=False),
        sa.Column("created_role_assignment_id", sa.UUID(), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("certified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "certificate_hash IS NULL OR certificate_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_clearing_cycles_certificate_hash_sha256"),
        ),
        sa.CheckConstraint(
            "input_hash IS NULL OR input_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_clearing_cycles_input_hash_sha256"),
        ),
        sa.CheckConstraint(
            "result_hash IS NULL OR result_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_clearing_cycles_result_hash_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','COLLECTING_SNAPSHOTS','PREPARING_NODES','PREPARED','PROPOSED','VERIFYING','COMMIT_CERTIFIED','APPLYING','COMMITTED_PENDING_APPLY','RECONCILED','PREPARE_EXPIRED','REJECTED','CONFLICT','CANCELLED')",
            name=op.f("ck_federated_clearing_cycles_status_allowed"),
        ),
        sa.CheckConstraint(
            "period_end > period_start", name=op.f("ck_federated_clearing_cycles_period_ordered")
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_federated_clearing_cycles_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["identity.members.id"],
            name=op.f("fk_federated_clearing_cycles_created_by_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["identity.users.id"],
            name=op.f("fk_federated_clearing_cycles_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_clearing_cycles_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_role_assignment_id"],
            ["identity.role_assignments.id"],
            name=op.f("fk_federated_clearing_cycles_created_role_assignment_id_role_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["federation.federated_clearing_policies.id"],
            name=op.f("fk_federated_clearing_cycles_policy_id_federated_clearing_policies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_clearing_cycles")),
        sa.UniqueConstraint("coordinator_node_code", "cycle_code", name="uq_federated_cycle_code"),
        schema="federation",
    )
    op.create_index(
        "ix_federated_cycles_status",
        "federated_clearing_cycles",
        ["status", "updated_at"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "federated_clearing_conflicts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("node_code", sa.String(length=63), nullable=False),
        sa.Column("conflict_code", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("evidence_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detected_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','RESOLVED')",
            name=op.f("ck_federated_clearing_conflicts_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_federated_clearing_conflicts_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["detected_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_clearing_conflicts_detected_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_clearing_conflicts")),
        schema="federation",
    )
    op.create_index(
        "ix_federated_conflicts_cycle_status",
        "federated_clearing_conflicts",
        ["cycle_id", "status"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "federated_clearing_proofs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("proof_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proof_hash", sa.String(length=71), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "proof_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_clearing_proofs_proof_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_clearing_proofs_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_federated_clearing_proofs_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_clearing_proofs")),
        sa.UniqueConstraint(
            "created_event_id", name=op.f("uq_federated_clearing_proofs_created_event_id")
        ),
        sa.UniqueConstraint("cycle_id", name="uq_federated_proof_cycle"),
        schema="federation",
    )
    op.create_table(
        "federated_clearing_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("proposal_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_hash", sa.String(length=71), nullable=False),
        sa.Column("result_hash", sa.String(length=71), nullable=False),
        sa.Column("coordinator_signature", sa.LargeBinary(), nullable=False),
        sa.Column("signer_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_clearing_proposals_input_hash_sha256"),
        ),
        sa.CheckConstraint(
            "result_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_clearing_proposals_result_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_clearing_proposals_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_federated_clearing_proposals_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_clearing_proposals")),
        sa.UniqueConstraint(
            "created_event_id", name=op.f("uq_federated_clearing_proposals_created_event_id")
        ),
        sa.UniqueConstraint("cycle_id", name="uq_federated_proposal_cycle"),
        schema="federation",
    )
    op.create_table(
        "federated_commit_certificates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("certificate_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("certificate_hash", sa.String(length=71), nullable=False),
        sa.Column("coordinator_signature", sa.LargeBinary(), nullable=False),
        sa.Column("signer_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column("certified_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "certificate_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_commit_certificates_certificate_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_commit_certificates_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_federated_commit_certificates_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_commit_certificates")),
        sa.UniqueConstraint("certificate_hash", name="uq_commit_certificate_hash"),
        sa.UniqueConstraint(
            "created_event_id", name=op.f("uq_federated_commit_certificates_created_event_id")
        ),
        sa.UniqueConstraint("cycle_id", name="uq_commit_certificate_cycle"),
        schema="federation",
    )
    op.create_table(
        "federated_input_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("node_code", sa.String(length=63), nullable=False),
        sa.Column("snapshot_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=71), nullable=False),
        sa.Column("checkpoint_hash", sa.String(length=71), nullable=False),
        sa.Column("node_signature", sa.LargeBinary(), nullable=False),
        sa.Column("signer_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("accepted_event_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checkpoint_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_input_snapshots_checkpoint_hash_sha256"),
        ),
        sa.CheckConstraint(
            "snapshot_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_input_snapshots_snapshot_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_input_snapshots_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_federated_input_snapshots_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_input_snapshots")),
        sa.UniqueConstraint(
            "accepted_event_id", name=op.f("uq_federated_input_snapshots_accepted_event_id")
        ),
        sa.UniqueConstraint("cycle_id", "node_code", name="uq_federated_snapshot_node"),
        schema="federation",
    )
    op.create_table(
        "inter_node_obligations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("home_node_code", sa.String(length=63), nullable=False),
        sa.Column("debtor_node_code", sa.String(length=63), nullable=False),
        sa.Column("creditor_node_code", sa.String(length=63), nullable=False),
        sa.Column("unit_code", sa.String(length=32), nullable=False),
        sa.Column("original_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("outstanding_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column(
            "cleared_amount",
            sa.Numeric(precision=38, scale=12),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("source_reference", sa.String(length=200), nullable=False),
        sa.Column("source_event_hash", sa.String(length=71), nullable=False),
        sa.Column("liquidity_class", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("prepared_cycle_id", sa.UUID(), nullable=True),
        sa.Column("prepared_input_hash", sa.String(length=71), nullable=True),
        sa.Column("prepared_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "source_event_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_inter_node_obligations_source_hash_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('CONFIRMED','PREPARED','PARTIALLY_CLEARED','CLEARED','DISPUTED','CANCELLED')",
            name=op.f("ck_inter_node_obligations_status_allowed"),
        ),
        sa.CheckConstraint(
            "debtor_node_code <> creditor_node_code",
            name=op.f("ck_inter_node_obligations_parties_distinct"),
        ),
        sa.CheckConstraint(
            "home_node_code IN (debtor_node_code, creditor_node_code)",
            name=op.f("ck_inter_node_obligations_home_party"),
        ),
        sa.CheckConstraint(
            "original_amount > 0 AND outstanding_amount >= 0 AND cleared_amount >= 0 AND outstanding_amount + cleared_amount = original_amount",
            name=op.f("ck_inter_node_obligations_amounts_consistent"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_inter_node_obligations_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_inter_node_obligations_created_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_inter_node_obligations_prepared_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inter_node_obligations")),
        schema="federation",
    )
    op.create_index(
        "ix_inter_node_obligations_home_status",
        "inter_node_obligations",
        ["home_node_code", "status", "unit_code"],
        unique=False,
        schema="federation",
    )
    op.create_index(
        "ix_inter_node_obligations_parties",
        "inter_node_obligations",
        ["debtor_node_code", "creditor_node_code"],
        unique=False,
        schema="federation",
    )
    op.create_table(
        "node_apply_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("node_code", sa.String(length=63), nullable=False),
        sa.Column("certificate_hash", sa.String(length=71), nullable=False),
        sa.Column("receipt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("receipt_hash", sa.String(length=71), nullable=False),
        sa.Column("node_signature", sa.LargeBinary(), nullable=False),
        sa.Column("signer_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("applied_count", sa.Integer(), nullable=False),
        sa.Column("applied_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("accepted_event_id", sa.UUID(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "receipt_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_node_apply_receipts_receipt_hash_sha256"),
        ),
        sa.CheckConstraint(
            "applied_count >= 0 AND applied_amount >= 0",
            name=op.f("ck_node_apply_receipts_applied_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_apply_receipts_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_node_apply_receipts_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_apply_receipts")),
        sa.UniqueConstraint(
            "accepted_event_id", name=op.f("uq_node_apply_receipts_accepted_event_id")
        ),
        sa.UniqueConstraint("cycle_id", "node_code", name="uq_apply_receipt_node"),
        schema="federation",
    )
    op.create_table(
        "node_clearing_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("node_code", sa.String(length=63), nullable=False),
        sa.Column("approval_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approval_hash", sa.String(length=71), nullable=False),
        sa.Column("node_signature", sa.LargeBinary(), nullable=False),
        sa.Column("signer_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("accepted_event_id", sa.UUID(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "approval_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_node_clearing_approvals_approval_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_clearing_approvals_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_node_clearing_approvals_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_clearing_approvals")),
        sa.UniqueConstraint(
            "accepted_event_id", name=op.f("uq_node_clearing_approvals_accepted_event_id")
        ),
        sa.UniqueConstraint("cycle_id", "node_code", name="uq_clearing_approval_node"),
        schema="federation",
    )
    op.create_table(
        "node_prepare_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("node_code", sa.String(length=63), nullable=False),
        sa.Column("receipt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("receipt_hash", sa.String(length=71), nullable=False),
        sa.Column("node_signature", sa.LargeBinary(), nullable=False),
        sa.Column("signer_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("accepted_event_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "receipt_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_node_prepare_receipts_receipt_hash_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_node_prepare_receipts_accepted_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_node_prepare_receipts_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_prepare_receipts")),
        sa.UniqueConstraint(
            "accepted_event_id", name=op.f("uq_node_prepare_receipts_accepted_event_id")
        ),
        sa.UniqueConstraint("cycle_id", "node_code", name="uq_prepare_receipt_node"),
        schema="federation",
    )
    op.create_table(
        "federated_obligation_applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("obligation_id", sa.UUID(), nullable=False),
        sa.Column("node_code", sa.String(length=63), nullable=False),
        sa.Column("certificate_hash", sa.String(length=71), nullable=False),
        sa.Column("amount_before", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("cleared_amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("amount_after", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("applied_event_id", sa.UUID(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "certificate_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_federated_obligation_applications_certificate_hash_sha256"),
        ),
        sa.CheckConstraint(
            "amount_before > 0 AND cleared_amount > 0 AND amount_after >= 0 AND amount_after = amount_before - cleared_amount",
            name=op.f("ck_federated_obligation_applications_amounts_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["applied_event_id"],
            ["journal.signed_events.event_id"],
            name=op.f("fk_federated_obligation_applications_applied_event_id_signed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["federation.federated_clearing_cycles.id"],
            name=op.f("fk_federated_obligation_applications_cycle_id_federated_clearing_cycles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["federation.inter_node_obligations.id"],
            name=op.f("fk_federated_obligation_applications_obligation_id_inter_node_obligations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_federated_obligation_applications")),
        sa.UniqueConstraint(
            "obligation_id", "certificate_hash", name="uq_obligation_certificate_application"
        ),
        schema="federation",
    )
    op.create_index(
        "ix_obligation_applications_cycle",
        "federated_obligation_applications",
        ["cycle_id", "node_code"],
        unique=False,
        schema="federation",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION federation.reject_federated_evidence_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'signed federated clearing evidence is append-only';
        END $$;

        CREATE TRIGGER trg_federated_input_snapshots_immutable
          BEFORE UPDATE OR DELETE ON federation.federated_input_snapshots
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();
        CREATE TRIGGER trg_federated_clearing_proposals_immutable
          BEFORE UPDATE OR DELETE ON federation.federated_clearing_proposals
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();
        CREATE TRIGGER trg_node_prepare_receipts_immutable
          BEFORE UPDATE OR DELETE ON federation.node_prepare_receipts
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();
        CREATE TRIGGER trg_node_clearing_approvals_immutable
          BEFORE UPDATE OR DELETE ON federation.node_clearing_approvals
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();
        CREATE TRIGGER trg_federated_commit_certificates_immutable
          BEFORE UPDATE OR DELETE ON federation.federated_commit_certificates
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();
        CREATE TRIGGER trg_node_apply_receipts_immutable
          BEFORE UPDATE OR DELETE ON federation.node_apply_receipts
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();
        CREATE TRIGGER trg_federated_obligation_applications_immutable
          BEFORE UPDATE OR DELETE ON federation.federated_obligation_applications
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();
        CREATE TRIGGER trg_federated_clearing_proofs_immutable
          BEFORE UPDATE OR DELETE ON federation.federated_clearing_proofs
          FOR EACH ROW EXECUTE FUNCTION federation.reject_federated_evidence_mutation();

        CREATE OR REPLACE FUNCTION federation.protect_federated_clearing_policy()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'federated clearing policy history cannot be deleted';
          END IF;
          IF (OLD.id, OLD.policy_code, OLD.policy_version, OLD.valuation_unit,
              OLD.algorithm_id, OLD.algorithm_version, OLD.decimal_scale,
              OLD.rounding_mode, OLD.minimum_operation, OLD.max_iterations,
              OLD.max_cycle_length, OLD.prepare_ttl_seconds, OLD.policy_payload,
              OLD.policy_hash, OLD.created_by_user_id, OLD.created_by_member_id,
              OLD.created_role_assignment_id, OLD.created_event_id, OLD.created_at)
             IS DISTINCT FROM
             (NEW.id, NEW.policy_code, NEW.policy_version, NEW.valuation_unit,
              NEW.algorithm_id, NEW.algorithm_version, NEW.decimal_scale,
              NEW.rounding_mode, NEW.minimum_operation, NEW.max_iterations,
              NEW.max_cycle_length, NEW.prepare_ttl_seconds, NEW.policy_payload,
              NEW.policy_hash, NEW.created_by_user_id, NEW.created_by_member_id,
              NEW.created_role_assignment_id, NEW.created_event_id, NEW.created_at) THEN
            RAISE EXCEPTION 'federated clearing policy terms are immutable';
          END IF;
          IF NEW.version <> OLD.version + 1 OR
             NOT (OLD.status = 'ACTIVE' AND NEW.status IN ('SUPERSEDED','REVOKED')) THEN
            RAISE EXCEPTION 'invalid federated clearing policy transition';
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER trg_federated_clearing_policies_state
          BEFORE UPDATE OR DELETE ON federation.federated_clearing_policies
          FOR EACH ROW EXECUTE FUNCTION federation.protect_federated_clearing_policy();
        CREATE OR REPLACE FUNCTION federation.protect_inter_node_obligation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'inter-node obligation history cannot be deleted';
          END IF;
          IF (OLD.id, OLD.home_node_code, OLD.debtor_node_code, OLD.creditor_node_code,
              OLD.unit_code, OLD.original_amount, OLD.source_reference,
              OLD.source_event_hash, OLD.created_event_id, OLD.created_at)
             IS DISTINCT FROM
             (NEW.id, NEW.home_node_code, NEW.debtor_node_code, NEW.creditor_node_code,
              NEW.unit_code, NEW.original_amount, NEW.source_reference,
              NEW.source_event_hash, NEW.created_event_id, NEW.created_at) THEN
            RAISE EXCEPTION 'inter-node obligation source evidence is immutable';
          END IF;
          IF NEW.version <> OLD.version + 1 THEN
            RAISE EXCEPTION 'inter-node obligation version must advance exactly once';
          END IF;
          IF NOT (
            (OLD.status = 'CONFIRMED' AND NEW.status IN ('PREPARED','DISPUTED','CANCELLED')) OR
            (OLD.status = 'PARTIALLY_CLEARED' AND NEW.status IN ('PREPARED','DISPUTED','CANCELLED')) OR
            (OLD.status = 'PREPARED' AND NEW.status IN
              ('CONFIRMED','PARTIALLY_CLEARED','CLEARED','DISPUTED')) OR
            (OLD.status = 'DISPUTED' AND NEW.status IN ('CONFIRMED','CANCELLED'))
          ) THEN
            RAISE EXCEPTION 'invalid inter-node obligation state transition';
          END IF;
          IF NEW.status = 'PREPARED' AND
             (NEW.prepared_cycle_id IS NULL OR NEW.prepared_input_hash IS NULL OR
              NEW.prepared_until IS NULL OR NEW.prepared_until <= now()) THEN
            RAISE EXCEPTION 'valid prepare lock is required';
          END IF;
          IF OLD.status <> 'PREPARED' AND
             (NEW.outstanding_amount <> OLD.outstanding_amount OR
              NEW.cleared_amount <> OLD.cleared_amount) THEN
            RAISE EXCEPTION 'only a prepared obligation may be cleared';
          END IF;
          IF OLD.status = 'PREPARED' AND
             (NEW.outstanding_amount <> OLD.outstanding_amount OR
              NEW.cleared_amount <> OLD.cleared_amount) AND
             (NEW.status NOT IN ('PARTIALLY_CLEARED','CLEARED') OR
              NEW.outstanding_amount >= OLD.outstanding_amount OR
              NEW.cleared_amount <= OLD.cleared_amount OR
              NEW.prepared_cycle_id IS NOT NULL OR NEW.prepared_input_hash IS NOT NULL OR
              NEW.prepared_until IS NOT NULL) THEN
            RAISE EXCEPTION 'clearing application is inconsistent';
          END IF;
          IF OLD.status = 'PREPARED' AND
             NEW.outstanding_amount = OLD.outstanding_amount AND
             NEW.cleared_amount = OLD.cleared_amount AND
             (NEW.status = 'CLEARED' OR
              (NEW.status = 'PARTIALLY_CLEARED' AND NEW.cleared_amount = 0)) THEN
            RAISE EXCEPTION 'empty clearing application has invalid state';
          END IF;
          IF NEW.status <> 'PREPARED' AND
             (NEW.prepared_cycle_id IS NOT NULL OR NEW.prepared_input_hash IS NOT NULL OR
              NEW.prepared_until IS NOT NULL) THEN
            RAISE EXCEPTION 'prepare lock must be cleared';
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER trg_inter_node_obligations_state
          BEFORE UPDATE OR DELETE ON federation.inter_node_obligations
          FOR EACH ROW EXECUTE FUNCTION federation.protect_inter_node_obligation();

        CREATE OR REPLACE FUNCTION federation.protect_federated_cycle()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'federated clearing cycle history cannot be deleted';
          END IF;
          IF (OLD.id, OLD.cycle_code, OLD.coordinator_node_code, OLD.policy_id,
              OLD.period_start, OLD.period_end, OLD.created_by_user_id,
              OLD.created_by_member_id, OLD.created_role_assignment_id,
              OLD.created_event_id, OLD.created_at)
             IS DISTINCT FROM
             (NEW.id, NEW.cycle_code, NEW.coordinator_node_code, NEW.policy_id,
              NEW.period_start, NEW.period_end, NEW.created_by_user_id,
              NEW.created_by_member_id, NEW.created_role_assignment_id,
              NEW.created_event_id, NEW.created_at) THEN
            RAISE EXCEPTION 'federated clearing cycle identity is immutable';
          END IF;
          IF NEW.version <> OLD.version + 1 THEN
            RAISE EXCEPTION 'federated clearing cycle version must advance exactly once';
          END IF;
          IF OLD.input_hash IS NOT NULL AND OLD.input_hash IS DISTINCT FROM NEW.input_hash OR
             OLD.result_hash IS NOT NULL AND OLD.result_hash IS DISTINCT FROM NEW.result_hash OR
             OLD.certificate_hash IS NOT NULL AND
               OLD.certificate_hash IS DISTINCT FROM NEW.certificate_hash THEN
            RAISE EXCEPTION 'federated clearing finality hashes are immutable';
          END IF;
          IF NOT (
            (OLD.status = 'DRAFT' AND NEW.status IN ('COLLECTING_SNAPSHOTS','CANCELLED')) OR
            (OLD.status = 'COLLECTING_SNAPSHOTS' AND NEW.status IN
              ('PREPARING_NODES','REJECTED','CONFLICT','CANCELLED')) OR
            (OLD.status = 'PREPARING_NODES' AND NEW.status IN
              ('PREPARED','PREPARE_EXPIRED','REJECTED','CONFLICT')) OR
            (OLD.status = 'PREPARED' AND NEW.status IN
              ('PROPOSED','PREPARE_EXPIRED','REJECTED','CONFLICT')) OR
            (OLD.status = 'PROPOSED' AND NEW.status IN
              ('VERIFYING','PREPARE_EXPIRED','REJECTED','CONFLICT')) OR
            (OLD.status = 'VERIFYING' AND NEW.status IN
              ('COMMIT_CERTIFIED','PREPARE_EXPIRED','REJECTED','CONFLICT')) OR
            (OLD.status = 'COMMIT_CERTIFIED' AND NEW.status IN
              ('APPLYING','COMMITTED_PENDING_APPLY','RECONCILED','CONFLICT')) OR
            (OLD.status = 'APPLYING' AND NEW.status IN
              ('COMMITTED_PENDING_APPLY','RECONCILED','CONFLICT')) OR
            (OLD.status = 'COMMITTED_PENDING_APPLY' AND NEW.status IN
              ('APPLYING','RECONCILED','CONFLICT'))
          ) THEN
            RAISE EXCEPTION 'invalid federated clearing cycle transition';
          END IF;
          IF NEW.status IN ('COMMIT_CERTIFIED','APPLYING','COMMITTED_PENDING_APPLY','RECONCILED')
             AND NEW.certificate_hash IS NULL THEN
            RAISE EXCEPTION 'commit certificate is required after economic finality';
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER trg_federated_clearing_cycles_state
          BEFORE UPDATE OR DELETE ON federation.federated_clearing_cycles
          FOR EACH ROW EXECUTE FUNCTION federation.protect_federated_cycle();

        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coop_app') THEN
            GRANT SELECT, INSERT, UPDATE ON
              federation.federated_clearing_policies,
              federation.federated_clearing_cycles,
              federation.inter_node_obligations,
              federation.federated_clearing_conflicts TO coop_app;
            GRANT SELECT, INSERT ON
              federation.federated_input_snapshots,
              federation.federated_clearing_proposals,
              federation.node_prepare_receipts,
              federation.node_clearing_approvals,
              federation.federated_commit_certificates,
              federation.node_apply_receipts,
              federation.federated_obligation_applications,
              federation.federated_clearing_proofs TO coop_app;
            REVOKE DELETE ON ALL TABLES IN SCHEMA federation FROM coop_app;
            REVOKE UPDATE, DELETE ON
              federation.federated_input_snapshots,
              federation.federated_clearing_proposals,
              federation.node_prepare_receipts,
              federation.node_clearing_approvals,
              federation.federated_commit_certificates,
              federation.node_apply_receipts,
              federation.federated_obligation_applications,
              federation.federated_clearing_proofs FROM coop_app;
          END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM federation.federated_clearing_cycles) OR
             EXISTS (SELECT 1 FROM federation.inter_node_obligations) OR
             EXISTS (SELECT 1 FROM federation.federated_clearing_policies) THEN
            RAISE EXCEPTION 'cannot downgrade 0018: federated clearing evidence would be lost';
          END IF;
        END $$;
        DROP FUNCTION IF EXISTS federation.protect_federated_cycle() CASCADE;
        DROP FUNCTION IF EXISTS federation.protect_federated_clearing_policy() CASCADE;
        DROP FUNCTION IF EXISTS federation.protect_inter_node_obligation() CASCADE;
        DROP FUNCTION IF EXISTS federation.reject_federated_evidence_mutation() CASCADE;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_obligation_applications_cycle",
        table_name="federated_obligation_applications",
        schema="federation",
    )
    op.drop_table("federated_obligation_applications", schema="federation")
    op.drop_table("node_prepare_receipts", schema="federation")
    op.drop_table("node_clearing_approvals", schema="federation")
    op.drop_table("node_apply_receipts", schema="federation")
    op.drop_index(
        "ix_inter_node_obligations_parties",
        table_name="inter_node_obligations",
        schema="federation",
    )
    op.drop_index(
        "ix_inter_node_obligations_home_status",
        table_name="inter_node_obligations",
        schema="federation",
    )
    op.drop_table("inter_node_obligations", schema="federation")
    op.drop_table("federated_input_snapshots", schema="federation")
    op.drop_table("federated_commit_certificates", schema="federation")
    op.drop_table("federated_clearing_proposals", schema="federation")
    op.drop_table("federated_clearing_proofs", schema="federation")
    op.drop_index(
        "ix_federated_conflicts_cycle_status",
        table_name="federated_clearing_conflicts",
        schema="federation",
    )
    op.drop_table("federated_clearing_conflicts", schema="federation")
    op.drop_index(
        "ix_federated_cycles_status", table_name="federated_clearing_cycles", schema="federation"
    )
    op.drop_table("federated_clearing_cycles", schema="federation")
    op.drop_index(
        "uq_federated_policy_active",
        table_name="federated_clearing_policies",
        schema="federation",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("federated_clearing_policies", schema="federation")
    # ### end Alembic commands ###
